### ISSUE TITLE
[BUG] Placeholders in the “Name” and “E-mail” fields do not correspond to the mockup on the sign up page.

### ISSUE THREAD

**Issue by oksana-mlynska** [BinaryStudioAcademy/bsa-2023-calmpal#102]
**Description:**
Placeholders in the “Name” and “E-mail” fields do not correspond to the mockup on the sign up page.

**Preconditions:**
The sign up page http://localhost:3000/sign-up is opened

**Environment:**
OS Windows 10
Browser Google Chrome
Version 116.0.5845.111

**Steps to reproduce:**

1. Pay attention to placeholders in the fields “Name” and “E-mail”

**Actual Result:**
Placeholder “Enter your name” is displayed in the “Name” field, placeholder “Enter your email” is displayed in the “E-mail” field.

**Expected Result:**
Placeholder “Please write your name” is displayed in the “Name” field, placeholder “name@gmail.com” is displayed in the “E-mail” field.

**Visual Proof (screenshots, videos, text):**

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140756353/bf99acea-051c-4348-ad77-467384aab478)

**Severity:**
Trivial (S4)

**Comment by Nanaier** [comment]
@Liza-Veis I think this one was done in my latest pull request 

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/90211108/a571cbfe-2139-4d6c-91a9-0f88e4b80ec3)

**Comment by liza-veis** [comment]
@Nanaier this issue is for placeholder texts, so it's still relevant

**Comment by Nanaier** [comment]
I see it now - thanks for the clarification

**Comment by Ekit18** [comment]
@oksana-mlynska 

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/92929504/5ee25ca2-347e-42f4-b2e6-d42f1c8a69c5)

same for email

**Comment by oksana-mlynska** [comment]
@Ekit18 ok, then I will need to clarify this with Liza
