### ISSUE TITLE
[BUG] Home button and Logo on the side bar is not clickable in Safari

### ISSUE THREAD

**Issue by k-mlch** [BinaryStudioAcademy/bsa-2023-calmpal#105]
Description: Home button and Logo on the side bar is not clickable in Safari

Open http://localhost:3000/sign-in and click on the Home button or Logo on the sidebar

**Actual Result:**
It doesn't redirect the user to another page

**Expected Result:**
It should redirect the user to the http://localhost:3000/ page and the Home button should be highlighted according to the design

**Comment by Nanaier** [comment]
@k-mlch hey - did you sign up before trying to navigate to http://localhost:3000/ ? Cause it is a protected route, so you would need to have a valid token to navigate to the root page. I tried the same thing in Safari and It seems to work fine for me - but maybe I'm missing something...

**Comment by k-mlch** [comment]
It seems like i just wasn't aware of this logic. And no, i didn't sign in before navigating to http://localhost:3000/, but i don't have this issue in Chrome browser, shouldn't it be consistent among all the browsers then?

**Comment by k-mlch** [comment]
This ticket is closed because it was determined that this issue is not a bug, but rather a feature, because http://localhost:3000/ is a protected route

**Comment by k-mlch** [comment]
This ticket is closed because it was determined that this issue is not a bug, but rather a feature, because http://localhost:3000/ is a protected route
