### ISSUE TITLE
[BUG] Header component is not responsive in Safari browser

### ISSUE THREAD

**Issue by k-mlch** [BinaryStudioAcademy/bsa-2023-calmpal#107]
**Description:**
Header component is not responsive in Safari browser

**Environment:**
Browser: Safari 16.1 

**Steps to reproduce:**

1. Open http://localhost:3000/ in Safari browser with 950 width resolution or less 

**Actual Result:**
Header is not responsive

**Expected Result:**
The header should be adapted to the screen size

**Visual Proof (screenshots, videos, text):**

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140718705/b4ac10a8-bdec-47a5-8857-4cbc17f464ef)

**Comment by juanc-escobar** [comment]
I think I already know what is the issue but I have two questions:

if I find the fix what should I do? Should I post it in the comments or where do I submit it for PR?

are you testing on Mac (Safari native environment) or are you using some kind of emulator so we can use the same to test it out?

**Comment by k-mlch** [comment]
@juanc-escobar i'm testing it on Mac (Safari native environment) and i'm not sure about your first question, i think it's better to ask @Liza-Veis

**Comment by liza-veis** [comment]
@juanc-escobar yes, you should create a PR with the fix, just usual flow, the same as for other issues

**Comment by juanc-escobar** [comment]
thanks, once I get out of work I will try the solution.

**Comment by juanc-escobar** [comment]
I did a pull request so if everything is ok it should be ready for you to test again, since I used an emulator and not the real Safari there may be some differences but for this particular task, it will work fine.
