### ISSUE TITLE
Sign In should return the same response as Sign Up

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2023-calmpal#112]
**Description:**
Sign In should return token and user in the body as for Sign Up

**Steps to reproduce:**

1. make a sign in request from postman

**Actual Result:**
Sign In returns only user without token

**Expected Result:**
Sign In returns the same result as Sign Up

**Visual Proof (screenshots, videos, text):**
![image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/64521658/ee86fcac-05ea-460e-bdb0-f7db736425b2)

**Severity:**
Critical (S1)

**Comment by HIMDanny** [comment]
@Liza-Veis, do we also need the `passwordHash` and `passwordSalt` properties on sign-in response?

**Comment by liza-veis** [comment]
no, we should not return neither passwordHash nor passwordSalt for both sign-up/sign-in, these are internal properties

**Comment by HIMDanny** [comment]
should I also remove them from sign-up, or it will be another issue?

**Comment by liza-veis** [comment]
yes, let's remove this, this is critical for security 🥲

**Comment by HIMDanny** [comment]
sure)

**Comment by HIMDanny** [comment]
@Liza-Veis. could you help me decide? I created a `signIn` method to return a correct response. I am thinking about two options: get a `UserEntiry` from `verifyLoginCredentials` in the controller and then pass it as a parameter in the `signIn` and call `toObject` inside, or pass the id to the method and then make a request to get a user from db. What would you recommend?

**Comment by liza-veis** [comment]
first option with controller

**Comment by HIMDanny** [comment]
thanks! Wait for the pr)
