### ISSUE TITLE
Profile settings layout

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2023-calmpal#113]
- [x] Layout
- [x] Common checkbox component
- [x] Setting component  
- [x] Add profile button to header #54 
- [x] When user presses profile button, they should be redirected to profile screen with only one item for now (Notifications and Reminders)
- [x] After user presses "Notifications and Reminders" button, they should be redirected to settings page (leave only Allow Notifications setting for now)

<img width="327" alt="Screenshot 2023-08-30 at 08 58 13" src="https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/64521658/14e804bc-c57f-441d-b43f-14fab193d7b5">
<br />
<img width="244" alt="Screenshot 2023-08-30 at 15 03 39" src="https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/64521658/911d9ca9-810b-4888-8817-cdc3dbf8a83b">
<br />
<img width="221" alt="Screenshot 2023-08-30 at 08 59 25" src="https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/64521658/7d3b6937-48a0-4bdb-882c-1282831f55cb">

**User Story:**
As a user, I want to be able to access my profile and manage my notification preferences easily.

**Acceptance Criteria:**
- "Profile" button should be located on the header of the Chat screen
- When the user clicks on the "Profile" button on the Chat screen, they should be redirected to the Profile screen
- On the Profile screen, there should be a single item visible, labeled as "Notifications and Reminders"
- When the user taps on the "Notifications and Reminders" button, they should be redirected to the "Settings" screen
- On the "Settings" page the "Allow Notifications" setting should be presented as a toggle switch.
- The user should be able to switch the setting on (enabled) or off (disabled).
- At any point in the process, the user should be able to navigate back to the previous screen using back button

**Comment by iamAlinaaa** [comment]
@Liza-Veis can i ask you some questions ?
i will make for now : 
- Common checkbox component 
- Setting component (leave only Allow Notifications setting for now) 
- profile button component (should it be reusable? because i see we have some )
- Also should i somehow add Setting component to the screen  (or i should create separate screen ) or to show up when button clicked?
 and i guess i have to wait till #54 be merged to lay the button at the header

**Comment by liza-veis** [comment]
> profile button component (should it be reusable? because i see we have some )

yes

> Also should i somehow add Setting component to the screen (or i should create separate screen ) or to show up when button clicked?

good point, updated the issue a bit, we should have a separate stack navigation (profile) and we need to create a screen with list of options like in  https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/issues/54 and another screen for settings for the first option

> and i guess i have to wait till https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/issues/54 be merged to lay the button at the header

yes
