### ISSUE TITLE
Update swagger documentation

### ISSUE THREAD

**Issue by oksana-mlynska** [BinaryStudioAcademy/bsa-2023-calmpal#121]
- [x] Add "fullName" to request body for /auth/sign-up request in swagger documentation

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140756353/310d0714-4c44-42aa-9200-ebbd336c6612)

- [x] Add to responses description for 400 Bad Request for Sign up request
- [x] Add to responses description for 401 Unauthorized for Sign in request
- [x] Add to responses description for 404 User not found for Sign in request

**Comment by HIMDanny** [comment]
@oksana-mlynska, should I also update the /auth/sign-up 201 response?

**Comment by oksana-mlynska** [comment]
@HIMDanny if you mean add token, then yes, let's update
