### ISSUE TITLE
User should be redirected to the main page after sign-up/sign-in

### ISSUE THREAD

**Issue by oksana-mlynska** [BinaryStudioAcademy/bsa-2023-calmpal#123]
**Actual result** 

After successfull requests for sign up and sign in the same page with blank input fields is opened

**Expected result**

The main page is opened after successfull sign-up/sign-in

**Additional information**

Reproduced both locally and by deployment link.

**Comment by dmytro-kucherenko** [comment]
@oksana-mlynska After signing up user will be automatically redirected to survey page, so maybe suggested behaviour only relates to sign in page?

**Comment by oksana-mlynska** [comment]
@Dmytro-Kucherenko just a moment, I will clarify this

**Comment by oksana-mlynska** [comment]
@Dmytro-Kucherenko answer from coaches: until we add survey, we should redirect to main page from both pages

**Comment by dmytro-kucherenko** [comment]
Okay, I understand

**Comment by oksana-mlynska** [comment]
Currently due to latest changes users who haven't completed survey are redirected to Survey page after sign up/sign in. So the task in the issue is not fully relevant anymore
