### ISSUE TITLE
Make names of buttons and links consistent on all pages on both mobile and frontend

### ISSUE THREAD

**Issue by k-mlch** [BinaryStudioAcademy/bsa-2023-calmpal#124]
Make names of buttons and links consistent on all pages on both mobile and frontend 

Pls follow the example on this mockup from Figma:

<img width="265" alt="image" src="https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140718705/7f8072ac-8596-461b-8549-0677da035859">

**Actual result:** 
on mobile (both sign in & sign up pages), names of links and fields: Sign Up, Sign In, Email
on frontend (sign in page): Email
Placeholder (mobile sign up page): Enter your full name

**Expected result:** 
on mobile both sign in & sign up pages), names of links and fields: Sign up, Sign in, E-mail
on frontend (sign in page): E-mail
Placeholder (mobile sign up page): Enter your name

**Comment by liza-veis** [comment]
@k-mlch hey, for now let's keep all placeholders in the following style "Enter your <field name>". Could you adjust the issue description according to this?

**Comment by k-mlch** [comment]
@Liza-Veis i've adjusted description
