### ISSUE TITLE
[BUG] Error is displayed on the 'Sign Up' screen after redirection from 'Sign in' screen

### ISSUE THREAD

**Issue by oksana-mlynska** [BinaryStudioAcademy/bsa-2023-calmpal#128]
**Description:**
Error 'User is not is authorized' is displayed on the 'Sign Up' screen after redirection from the 'Sign in' screen

**Preconditions:**
The 'Sign up' screen is opened

**Environment:**
Virtual mobile device

**Steps to reproduce:**

1. Click on the 'Sign up' link
2. Pay attention to the error message which is displayed on 'Sign up' screen

**Actual Result:**
Error 'User is not is authorized' is displayed on the 'Sign Up' screen even though 'Sign up' button was not tapped and input fields are empty.

**Expected Result:**
Nor errors are displayed.

**Visual Proof (screenshots, videos, text):**

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140756353/96827026-1413-4618-8ed1-e5fe4a696f00)

**Severity:**
Major (S2)

**Additional information:**
Terminal with backend running shows the following error once the 'Sign up' screen is opened.
[14:50:04.876] ERROR (12028): [Auth Error]: 401 тАФ User is not authorized.

**Comment by BrianSammit** [comment]
Fix it.



![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/64173189/2a5a7b73-c646-41c8-b313-a0fd66a3d294)
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/64173189/6510737b-6346-47c3-a317-729f70456aba)
