### ISSUE TITLE
The loader shouldn't be shown instead of form when the user presses sign in/sign up button

### ISSUE THREAD

**Issue by k-mlch** [BinaryStudioAcademy/bsa-2023-calmpal#129]
**Description:** The loader shouldn't be shown instead of the form when the user logs in to the app, it should be shown inside the sign-in/sign-up button and the page/form should remain unchanged 

**Environment**: http://calmpal-alb-development-453467742.eu-west-1.elb.amazonaws.com/
**Steps to Reproduce:**

1. Fill Sign In form with invalid credentials
2. Click Sign in button

**Actual result:** The loader is shown instead of the form and the form data is erased
**Expected result**: The loader should be shown inside the sign-in/sign-up button and the page/form should remain unchanged

https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140718705/90bbc72a-0b78-4048-a574-4be9382fe064

**Comment by liza-veis** [comment]
@HIMDanny pay attention to ux best practises

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/64521658/1fca9557-15d7-4845-a620-137b85a96a49)

**Comment by HIMDanny** [comment]
@Liza-Veis, can I get rid of the loader in the app component? Or should I add one more check for it, for example, is it the first mount of the component?

![image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/58943798/a2e718e7-7bcd-455c-8786-3dcc6164e7c9)
