### ISSUE TITLE
[BUG] Input field remains highlited with red after trying to Sign up with empty field and then tapping on this field.

### ISSUE THREAD

**Issue by oksana-mlynska** [BinaryStudioAcademy/bsa-2023-calmpal#131]
**Description:**
 Input field remains highlited with red after trying to Sign up with empty field and then tapping on this field.

**Preconditions:**
The 'Sign up' screen is opened

**Environment:**
Mobile virtual device

**Steps to reproduce:**

1. Leave all input fields and click on the 'Sign up' button
2. Click on one of the input fields
3. Pay attention to the border of the screen

**Actual Result:**
The border of the input field remains highlighted with a red color

**Expected Result:**
The Input field goes to active state and is highlighted with a dark blue color
(Expected result is based on how this functionality works on frontend side and on common practice)

**Visual Proof (screenshots, videos, text):**
Mobile screen

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140756353/cce54b32-5ab5-44ed-a254-82aff5018a5e)

Frontend screen

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140756353/0aa6cb90-74a2-47b3-9bf5-b25ff0b95d4a)

**Additional information**
The same bug is reproduced on 'Sign in' screen
Once the user starts typing something in the field, it goes to active state as expected

**Severity:**
Trivial (S4)

**Comment by liza-veis** [comment]
@oksana-mlynska Hey! I think it's an expected and usual behavior for the forms

**Comment by oksana-mlynska** [comment]
@Liza-Veis it just works differently on web and mobile now. I added screen from frontend. Once the cursor is in the field it is not highlited with red. And marked this is as trivial. If you say it's not a bug, then I will colse the issue

**Comment by liza-veis** [comment]
Yes, you are right, it's a bug
