### ISSUE TITLE
Sign In/Sign Up pages are not responsive in Safari browser for mobile devices

### ISSUE THREAD

**Issue by k-mlch** [BinaryStudioAcademy/bsa-2023-calmpal#133]
**Description:**
Sign In/Sign Up pages are not responsive in Safari browser for mobile devices

UPDATE: other pages like survey, home, meditations, chat, journal & my profile are not responsive either and should be fixed as part of this ticket too

**Environment:**
Browser: Safari 16.1

**Steps to reproduce:**

Open http://localhost:3000/ in Safari browser with 1000 width resolution or less
**Actual Result:**
Sign In/Sign Up pages are not responsive

**Expected Result:**
The Sign In/Sign Up pages should be adapted to the screen size

Visual Proof (screenshots, videos, text):

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140718705/c8fbb9df-42dc-49d8-a3be-28bcf7d30603)

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140718705/0d56375c-f6cb-463d-925a-a24683435d55)

**Comment by oksana-mlynska** [comment]
The bug is reproduced by a new deployment link https://development.app.calmpal.com/sign-in on the Physical device (iPhone 11pro max) 

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140756353/ddb0ce01-38e1-4600-be1e-30c9990c8aaf)



![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140756353/a6f19378-2c8b-441f-bf14-14d4ee58c819)

**Comment by k-mlch** [comment]
the logic of sidebars should be working the same as described in [ticket](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/issues/223) in Safari browser and it should be implemented and tested as part of this ticket

**Comment by juanc-escobar** [comment]
@ k-mlch

can you recheck this, I don't have a Mac to test but I use an emulator, and it is showing me it works appropriately, it may have been fixed in previous updates. 

![image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/107894952/7d66d18b-8375-4219-8eb5-b7fcd046cfa3)

**Comment by k-mlch** [comment]
@juanc-escobar it looks like this for me in safari browser on my PC 
<img width="698" alt="image" src="https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140718705/4391e831-2ecc-467f-805a-cada9aa1d28c">

**Comment by k-mlch** [comment]
@juanc-escobar let me download the latest version of the Safari and recheck it again, because for now i have 16.1 version

**Comment by juanc-escobar** [comment]
OK, if it does not work I may have an idea of what it could be but if I can not test it and see the changes it would be too complicated, I will also look if can find another way to test the Safari browser If not I will unassing my self from the task and ask if someone is developing in Mac environment so they can check this out.

**Comment by k-mlch** [comment]
@juanc-escobar seems like it's working fine in the latest version, at least from the smoke test

@Liza-Veis in such a case if it works okay in the latest Safari version but doesn't work in the oldest versions ( for example Safari 16.1) should we fix it or not?

**Comment by liza-veis** [comment]
let's support only latest versions

**Comment by k-mlch** [comment]
i close this issue because everything is working fine in Safari 16.6 (side bar works properly, sign in/sing up and survey pages are responsive and other pages too)
