### ISSUE TITLE
Error is shown when an unauthorized user opens the web app for the first time

### ISSUE THREAD

**Issue by k-mlch** [BinaryStudioAcademy/bsa-2023-calmpal#134]
**Description:**
Error is shown when an unauthorized user opens the web app for the first time 

**Steps to reproduce:**
1. Open http://localhost:3000/ or http://calmpal-alb-development-453467742.eu-west-1.elb.amazonaws.com/ as unauthorized user 

**Actual Result:**
'User is not authorized' error message is shown 

http://localhost:3000/api/v1/auth/authenticated-user
401 Status Code
{"message":"User is not authorized.","errorType":"AUTHORIZATION"}

**Expected Result:**
No errors are present 

**Visual Proof (screenshots, videos, text):**

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140718705/0884bb83-701a-493e-a64a-bbef73531b06)

**Comment by OlenaYatseniuk** [comment]
Fixed it.
https://user-images.githubusercontent.com/102380564/264714758-419e98b1-85d0-4881-acde-94887656ce8e.png
