### ISSUE TITLE
Replace app logo with updated one

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2023-calmpal#143]
- [ ] replace app logo for sign up/sign in, also we will need to change some styles to make it look like on design
- [ ] all styles should be responsible, and changed according to new design (pay attention to mobile screens, before we had custom label instead of logo)
- [ ] re-generate new favicons/android/apple icons needed for PWA that were added in #41 

<img width="217" alt="Screenshot 2023-09-01 at 04 47 00" src="https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/64521658/e2a8e4ad-41f1-43a4-b983-3e39741fb0d9">

User story:
As a user, I want to see the logo so that I can easily identify and recognize the brand associated with the application.

Acceptance criteria: 
1. Updated favicons, Android icons, and Apple icons are required to support the Progressive Web App (PWA) functionality introduced in task #41
2. The styles of the sign-up and sign-in pages are updated to align with the new design guidelines
3. App logo on the sign-up and sign-in pages are replaced with the new design
4. Logo looks the same as on the design

**Comment by juanc-escobar** [comment]
Hi @Liza-Veis ,

I've started working on the task. Based on the design specifications, it appears that we have about three different logo variations.

Before I advance any more, I wanted to clarify a few things to ensure alignment with the team's vision and practices.
Would it be acceptable to utilize the HTML `<picture>` element along with multiple `<source>` elements to manage these different logo variants?

Alternatively, is there a preference to develop a React component that handles color changes dynamically?

Personally, I prefer using the full capabilities of HTML and CSS, especially given that SVGs are lightweight and won't impact performance. Using three distinct logo files seems like a straightforward approach.
However, as this is a collaborative project, I'd like to get your thoughts to ensure that my solution will align with everyone's needs and expectations.

What limitations should I consider for this task?

**Comment by liza-veis** [comment]
Hey! yes use can use picture, but only for images that should be placed in the same position but will be different for different dimensions.
