### ISSUE TITLE
Design of the Survey page is not responsive on height less than 800 px

### ISSUE THREAD

**Issue by oksana-mlynska** [BinaryStudioAcademy/bsa-2023-calmpal#147]
Design of the Survey page is not responsive and 'Continue' button is not active on height of screen less than 800 px
Reproduced both on localhost and by deployment link http://calmpal-alb-development-453467742.eu-west-1.elb.amazonaws.com/sign-up/survey

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140756353/f24a006a-100c-4a2d-abb4-88c7df6907dc)

**Comment by oksana-mlynska** [comment]
The bug from the screen is not reproduced anymore. But I have a question. @Liza-Veis wouldn't it be better if the options moved to the center when you reduce the height to save the proportions of the layout? Now they stay static and we have a lot of unnesessary space in the upper side of the screen

https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140756353/7cf1a30c-a75b-4841-b660-ced4d239317f

**Comment by liza-veis** [comment]
Let's leave it as it is for now
