### ISSUE TITLE
Journal functionality

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2023-calmpal#157]
- [x] Add journal_entries table with the following columns:
  - title - varchar 300
  - text - text
  - createdAt
  - updatedAt
- [x] When user opens journal item in sidebar load list of all journal_entries, and display them in the left part of the screen, styles are the same as for chat sidebar #77 
- [x] Update db schema in readme (remove journal_topics table, update columns)
- [x] Add rotes to swagger

Note: no need to implement the right part of the screen (note preview), we will do this in another task.

<img width="116" alt="Screenshot 2023-09-02 at 20 52 01" src="https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/64521658/8a69eb43-dfff-4ae0-b351-c5dbf7923c24">

<img width="880" alt="Screenshot 2023-09-02 at 20 39 49" src="https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/64521658/6b97cc6c-86d4-4cca-8c7f-2f84036d3e8d">

**Comment by Nanaier** [comment]
@Liza-Veis should the functionality for the favorite chats be implemented?

**Comment by liza-veis** [comment]
No, not for now

**Comment by oksana-mlynska** [comment]
@Nanaier should the limit for the title be 300 chars? As now in Postman I am testing the post journal endpoint and I see that the limit is set to 255 symbols.

**Comment by Nanaier** [comment]
at the time of the creation of the table(and till now) our database schema had the title as type varchar and the max length for varchar is 255 characters
