### ISSUE TITLE
Add meditation entry funtionality

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2023-calmpal#160]
- [x] make topic_id optional
- [x] add an ability to create meditation with audio uploading (mp3 only for now) 
- [x] we will need to add additional fields to meditation_entries table to save audio url
- [x] update database schema and swagger
- [x] create a modal on ui (for now, we don't have design so just try to stick to the same style)
- [x] when user clicks add button at the top of meditations sidebar, "Add meditation" modal should appear

Note: we already have file uploading functionality #70, we should use it for saving audio

**Comment by dmytro-kucherenko** [comment]
@Liza-Veis Should user also enter meditation title in modal?

**Comment by liza-veis** [comment]
Yes

**Comment by dmytro-kucherenko** [comment]
@Liza-Veis Is it supposed to be made 2 separate requests from frontend in order to create file url and then create meditation entry with this url in body?

**Comment by liza-veis** [comment]
Yes
