### ISSUE TITLE
Add File uploading service to the Swagger

### ISSUE THREAD

**Issue by k-mlch** [BinaryStudioAcademy/bsa-2023-calmpal#176]
Add file uploading service that was created in [this ticket ](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/issues/70) to the Swagger documentation

**Comment by oksana-mlynska** [comment]
@OlenaYatseniuk where in swagger should we add token for this request? Usually, I do it with the help of such icon, but we don't have it in our swagger documentation.

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140756353/ed14d4dd-4023-47d4-a276-bc10479376d0)

UPD: When I try to authorize with the help of this button in the top, the request which demands authorization still respond with 401 status


![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140756353/8766199b-9276-4b02-acda-3062a5c8bb94)

**Comment by OlenaYatseniuk** [comment]
@oksana-mlynska  Yeah, I saw that. Do you open Swagger via localhost? It's better to test this route via Postman and with the deployment base URL, as it doesn't work in localhost because of credentials.
