### ISSUE TITLE
[BUG] User Password data is returned when user sends GET authenticated-user request

### ISSUE THREAD

**Issue by k-mlch** [BinaryStudioAcademy/bsa-2023-calmpal#177]
**Description:**
User Password data is returned when user sends Get Authenticated User request 

**Steps to reproduce:**

1. Send GET authenticated-user request with valid token

**Actual Result:**
User Password data is present in the response

**Expected Result:**
No user password data should be present in the response body

**Visual Proof (screenshots, videos, text):**

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140718705/d3101a06-40f1-43e2-913b-8af674dc1287)

**Comment by oksana-mlynska** [comment]
@HIMDanny also pay attention that schema in swagger does not correspond to the actual response body. 

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140756353/42cf550e-56a9-4fe4-b359-203a45564e5e)

**Comment by HIMDanny** [comment]
good point! I will change it as well
