### ISSUE TITLE
[BUG] White border around icons on sidebar is not clickable

### ISSUE THREAD

**Issue by k-mlch** [BinaryStudioAcademy/bsa-2023-calmpal#181]
**Description:**
Not whole parts of the buttons on the sidebar are clickable, the white circle around icons on the bar is not clickable

**Steps to reproduce:**

1. Navigate to the sidebar 
2. Click on the white border around the icon on the sidebar button in order to navigate to another page

**Actual Result:**
Only the blue icon side of the border is clickable 

**Expected Result:**
The whole button is clickable

**Visual Proof (screenshots, videos, text):**

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140718705/1d66e2d6-0ff5-4aba-ac95-9ff120a7f7d9)

**Comment by oksana-mlynska** [comment]
@Ekit18 the bug is still reproduced in Firefox browser

**Comment by Ekit18** [comment]
@oksana-mlynska 

https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/92929504/afa66ff2-9f00-4b1b-902f-98f771620cbd

**Comment by oksana-mlynska** [comment]
@Ekit18 now in Firefox worsk fine. @k-mlch could you please check in Safari?

**Comment by k-mlch** [comment]
@oksana-mlynska it works just fine in Safari
