### ISSUE TITLE
Add meditation timer

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2023-calmpal#182]
- [ ] add modal where user can select meditation duration
- [ ] add only predefined values for now - 5, 10, 20
- [ ] after user selects an item from meditations list #101  , modal should appear
- [ ] after user clicks start session in the modal, they should be redirected to the meditation player screen #170   and the sound should loop for that duration

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/64521658/8343b328-0fd1-4381-8744-4af0ae258029)

**Comment by Vika030718** [comment]
@Liza-Veis Could you please clarify one question: Can the user interact with other screen elements while the modal window is opened? For example, can he/she select another track without first closing the modal window?

**Comment by liza-veis** [comment]
As for me, modal should be closed in this case
