### ISSUE TITLE
[BUG] User not found error appears on Local environment after refreshing the page

### ISSUE THREAD

**Issue by k-mlch** [BinaryStudioAcademy/bsa-2023-calmpal#187]
**Description:**
User not found error appears after i log in with valid credentials and refresh the page

**Environment:**
http://localhost:3000/

**Steps to reproduce:**

1. Log in via valid credentials
2. Refresh the page

**Actual Result:**
User was navigated to http://localhost:3000/sign-in and User not found error appeared

{"message":"User with these credentials was not found.","errorType":"USERS"}

**Expected Result:**
The page refreshed, and no errors appeared

**Visual Proof (screenshots, videos, text):**

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140718705/a2b0c8be-fbfa-4b80-aecd-57ca8b9c0095)

**Comment by k-mlch** [comment]
The same issue appears on mobile after closing the app and opening it again


![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140718705/6072e8f5-bf06-4cb6-a374-c8acf4237fee)

**Comment by Ekit18** [comment]
@OlesiaTr i found solution to fix this bug. As i think you should remove modify('withoutPassword') from user repository. it`s probably useless. in this case password exist only in backend
