### ISSUE TITLE
Add meditation sidebar

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2023-calmpal#188]
- [x] Add meditation sidebar (everything except add button)
- [x] Leave only meditation item for now

Note: You can see some comments about responsiveness in this pr #75
 
![Messages Panel](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/64521658/2eedea55-be1e-429a-b1ae-5e46a2562db8)

**User story:**
As a user, I want to be able to navigate through meditation options and use search, so that I can quickly go to the option I need.

**Acceptance criteria:**
- The Meditation sidebar should be reachable from the main navigation menu.
- The first option from the Profile settings sidebar should be active when the user opens this page for the first time
- If a user clicks on the option from the Meditation sidebar, the appropriate page is opened and the option becomes active
- The active state of the selected option is saved if a user navigates to other menu sections
- The hover effect over the sidebar options is present
- The Profile settings sidebar is responsive for various screen sizes.
- On the mobile screen size user should be able to navigate back to the sidebar from the corresponding profile settings page
- Search field is present on the sidebar and enables the user to search the needed option (case-insensitive)

**Comment by Ekit18** [comment]
@Liza-Veis should i do it in this dark theme or do similar to figma?

**Comment by liza-veis** [comment]
What dark theme do you mean?

**Comment by Ekit18** [comment]
@Liza-Veis  i have this in screenshot))) sorry my bad

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/92929504/b40108b7-b32f-4105-a9e8-71f073daddcf)

**Comment by liza-veis** [comment]
For me it looks fine, maybe some light colors are inverted in github dark theme, design should be like in figma

**Comment by Ekit18** [comment]
@Liza-Veis could i modify chat-sidebar and user profile sidebar similar to this?

https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/92929504/9315d557-9932-4ddb-b013-6ea04af2f502

**Comment by liza-veis** [comment]
yes, but we also need to think about the way how we will get back to this screen when we get to meditation item. We were discussing this in this PR #75, so if you contact @vladyslavdobychin and come up to the one solution that would be nice

**Comment by Ekit18** [comment]
@Liza-Veis thx))

**Comment by liza-veis** [comment]
@Ekit18 I thought about it, let's leave it as on your recording for now without the back button, we will create a separate ticket for this, because we will need to make some other changes too. So for now it's ok, but please contact @vladyslavdobychin, that you both use one approach

**Comment by Ekit18** [comment]
ok

**Comment by dmytro-kucherenko** [comment]
@Liza-Veis You created issue with the point 'Add meditation sidebar (everything except add button)'. Should I add this add button afterwards in my issue #213 about meditation entry functionality?

**Comment by oksana-mlynska** [comment]
@Ekit18 It seems that the size of the header container is bigger the in other sections like chat or journal


![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140756353/9c4e9200-374f-4f8b-aecf-87b61597bc4d)

**Comment by oksana-mlynska** [comment]
@Ekit18 also in Chat and Journal section there is a hover effect when you go over sidebar options (shadow gets darker)

**Comment by Ekit18** [comment]
@oksana-mlynska this is fixing in this task https://github.com/orgs/BinaryStudioAcademy/projects/12/views/1?sliceBy%5Bvalue%5D=Ekit18&pane=issue&itemId=38010222

**Comment by oksana-mlynska** [comment]
@Ekit18 and hover also will be added? Also, the 'search' field is not highlighted as active when the user clicks on it.

**Comment by Ekit18** [comment]
@oksana-mlynska i will add search highlight. And also hover effects on chat/journal sidebar elements have been already added to dev

https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/92929504/58a17ce1-0613-4ec4-a416-d7d6577964cd

**Comment by oksana-mlynska** [comment]
@Ekit18 ok. then I will close this issue and wait when the one with improvements will be available for testing
