### ISSUE TITLE
Create chat functionality

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2023-calmpal#189]
- [x] when user opens chat page, list with all their chats should be loaded
- [x] if user have no chats or presses create chat button, new empty chat should be opened
- [x] when user sends a first message, new chat should be created and it should appear in a chat list (use mocked name for chat for now)

Note: you don't need to implement messages saving or loading the selected chat messages. Also, the functionality above is similar to chatgpt.

**Comment by HIMDanny** [comment]
@Liza-Veis, hey! Should I connect chat and current user via chat messages or is there a better solution?

**Comment by liza-veis** [comment]
Let's add members column to chats table and store user ids array in it

**Comment by HIMDanny** [comment]
@Liza-Veis, what do you think, do I need to create a method `findAuthenticatedUserChats` or just use `findAll` method for finding chats of the current user? Or even call a method `findAllByUserId`

**Comment by liza-veis** [comment]
If it's a chat service, then findAllByUserId

**Comment by HIMDanny** [comment]
@Liza-Veis, do I need to create an endpoint for creating a new chat or should the chat be created with the first sent message to the server (in this case with the send message endpoint)?

**Comment by HIMDanny** [comment]
And do I need to also create a chat-messages package with service, controller, etc.?

**Comment by liza-veis** [comment]
> do I need to create an endpoint for creating a new chat or should the chat be created with the first sent message to the server (in this case with the send message endpoint)?

yes, you need to create endpoint, and you should send a request to it after first message. 

> And do I need to also create a chat-messages package with service, controller, etc.?

yes, everything needed for your task

**Comment by HIMDanny** [comment]
> yes, you need to create endpoint, and you should send a request to it after first message.

but the chat message needs to have a `chat_id`. So the chat has to be created before adding a message to db. Please correct me, if I am mistaken

**Comment by HIMDanny** [comment]
Can we do it like this: when creating a message, `chat_id` would be an optional param, and if there is no `chat_id` we would create a new chat, otherwise, add a message to the existing chat.

**Comment by HIMDanny** [comment]
@Liza-Veis, could we create message package only with message.model, message.repository, message.entity and use it in chat.service? It looks logical, because functionalities are related to each other, but on the other side, it may lead to the situation when chat package has too much functionality.

**Comment by liza-veis** [comment]
> but the chat message needs to have a chat_id. So the chat has to be created before adding a message to db. Please correct me, if I am mistaken

after user sends their first message, we should create a chat first and after that create this message 

> Can we do it like this: when creating a message, chat_id would be an optional param, and if there is no chat_id we would create a new chat, otherwise, add a message to the existing chat.

no, do this as I described above

> could we create message package only with message.model, message.repository, message.entity and use it in chat.service? It looks logical, because functionalities are related to each other, but on the other side, it may lead to the situation when chat package has too much functionality.

yes, let's add chat package and chat-message package

**Comment by HIMDanny** [comment]
> after user sends their first message, we should create a chat first and after that create this message

did I understand it correctly that we can implement this on the frontend part with a help of two endpoints (create chat, create message)?

**Comment by Xxandder** [comment]
And also do we need to create message controllers? Or we can use only chat controller with its enpoint also for creating and getting messages?

**Comment by Xxandder** [comment]
> after user sends their first message, we should create a chat first and after that create this message
> 
> > Can we do it like this: when creating a message, chat_id would be an optional param, and if there is no chat_id we would create a new chat, otherwise, add a message to the existing chat.
> 
> no, do this as I described above

But we have two situations. the first - when user sends message in alreay created chat, so we should send in this case response with message, userId, chatId. But the second situation - when user sends message to an empty chat so we need to create chat and message. And here is the question(above) - do we need to create separate endpoints for chat creation and messages creation? We can just create add endpoint in chat.controller which is responsible for message creation. And in this endpoint call appropriate chat.service function in which we will call functions from chat.repository and message.repository to create both of them

**Comment by liza-veis** [comment]
@Xxandder @HIMDanny 

> did I understand it correctly that we can implement this on the frontend part with a help of two endpoints (create chat, create message)?

yes, depending on if there is a chat we will either send two requests or one

> And also do we need to create message controllers? Or we can use only chat controller with its enpoint also for creating and getting messages?

no we don't need controller for messages, let's use chat controller

> do we need to create separate endpoints for chat creation and messages creation? We can just create add endpoint in chat.controller which is responsible for message creation. And in this endpoint call appropriate chat.service function in which we will call functions from chat.repository and message.repository to create both of them

we should have separate endpoints for chat creation and message creation, like:
- `POST /chats` - create a chat
- `POST /chats/{chat_id}/messages`  - create a message

**Comment by Xxandder** [comment]
@Liza-Veis Thanks for the answer. But also want to clarify if it is better to create common slice with fields like: chats[], currentChatMessages[]? Or create separate slices?

**Comment by HIMDanny** [comment]
@Liza-Veis, we have a [chat slice](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/pull/85/files/5a3542c5dbf35ee36f50e2d7ce4fdda5c66862b0#diff-c8f76e33b1bfa4538bff0d78a38fb9b3929af5811c00a4ebf49bcaa3824d6e95) that was made by Oscar, but in my humble opinion, there is slightly inappropriate logic and types used. Can we rewrite this slice to match the created functionality?

**Comment by liza-veis** [comment]
Yes, you can modify it, let's have only one slice for chats

**Comment by Xxandder** [comment]
@Liza-Veis Do we need to add chat_id to our route when we in '/chat' page?

**Comment by liza-veis** [comment]
yes, of course, we should be able to see the same chat after page reload

**Comment by HIMDanny** [comment]
@Liza-Veis, am I right, that the new chat should appear on the top of the chat list? Or it is not necessary?

**Comment by liza-veis** [comment]
Yes, it should appear at the top

**Comment by HIMDanny** [comment]
so is it also better to return a chat list with newer chats on top on the backend, or we can do it on the frontend part only?

**Comment by liza-veis** [comment]
let's do this on backend

**Comment by Xxandder** [comment]
> we should have separate endpoints for chat creation and message creation, like:
> 
> * `POST /chats` - create a chat
> * `POST /chats/{chat_id}/messages`  - create a message

Do I still need to send chat_id in body of the reqiest when creating chat messages? Or get it from path?

**Comment by liza-veis** [comment]
no, take it from path
