### ISSUE TITLE
Chat functionality

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2023-calmpal#190]
- [x] when user selects a chat, all messages of this chat should be loaded
- [x] when user sends message to the chat it should be saved on the backend

Depends on create chat functionality #189

**Comment by Xxandder** [comment]
@Liza-Veis Hello, I want to clarify some implementing aspects not to redo everything in future, because I am not sure in exact way of implementing it. Am I right that I need to create separate package for messages with model/repository/entity/cervice/controller for backend?  I ask because my task is related to cp-189 and there is needed to create backend part for chats. And the same question for storage. Should I create separate slice or maybe we can create slice with something like this: store = {chats[], currentChatMessages[]}

**Comment by Xxandder** [comment]
@Liza-Veis Hello. I have two questions to clarify. 
1. Do I need to throw error when chat is not exists when user tries to create message with wrong chatId? The same for the senderId. 
2. What is the max length of the message?

**Comment by liza-veis** [comment]
1. Yes, if course, we should handle all cases
2. let's have 4000 chars limit

**Comment by liza-veis** [comment]
> Am I right that I need to create separate package for messages with model/repository/entity/cervice/controller for backend

yes, we need separate chat and chat-message packages, but we will have only one controller in chat package

> Should I create separate slice or maybe we can create slice with something like this: store = {chats[], currentChatMessages[]}

the second option - one slice with chat and currentChat properties

**Comment by Xxandder** [comment]
@Liza-Veis Do we really need "name" column in chat_messages table?


![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/111736110/102f07ca-0552-4a97-823b-79739446f47e)

**Comment by liza-veis** [comment]
No, we don't, remove it

**Comment by Xxandder** [comment]
@Liza-Veis Could you please clarify the next question? 
I created types for backend requests and responses for chat-messages. But I am not sure which fields are enough for project functionality. So in chat layout we can use only message text and senderId and it will be enough for current tasks. But maybe in future we will to edd extra functionality where chatId is needed. So can we use this type?:
```
type ChatMessageGetAllItemResponseDto = {
  id: number;
  senderId: number;
  message: string;
};
```

**Comment by liza-veis** [comment]
created and updatedAt should be returned as well

**Comment by liza-veis** [comment]
and let's return chatId too, so that we can detect the chat by message on frontend

**Comment by Xxandder** [comment]
ok, got it

**Comment by Xxandder** [comment]
And can I create separate package for chat-messages in shared folder? Just in backend I have separate package, in frontend chat-messages a placed at chat package and slice. So I am not sure how to imlement it in shared folder

**Comment by liza-veis** [comment]
yes, but we will have controller only in chat package

**Comment by KrychkovskaVira** [comment]
I just want to make sure, is it normal that created chats are currently available to all users?

**Comment by HIMDanny** [comment]
@KrychkovskaVira, it's not normal) I guess we should make a ticket for this to investigate further

**Comment by KrychkovskaVira** [comment]
@HIMDanny I meant, was it part of the task you were working on. Thank you!
