### ISSUE TITLE
Add chatbot

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2023-calmpal#193]
- [ ] we need to create OpenAi service 
    Note: we will mainly use it for chatbot and images generation, pay attention to this during service design
- [ ] create a user for the chatbot with role chatbot
- [ ] implement chatbot messaging 
    - should be a separate service
    - use simple prompt for now, but take into account that we will modify it using survey later
    - logic: user send message and then receives an answer from chatbot

Note: main messaging functionality will be implemented here #190, you don't need to implement it

**Comment by oksana-mlynska** [comment]
@Nanaier sometimes (not always) bot gives such an answer for a question What is your name?
Can we influence on it?

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140756353/8e345297-d5e9-4fab-aa18-50311a642137)

**Comment by oksana-mlynska** [comment]
@Nanaier it sometimes happens, that in a conversation bot uses the same sentances in its answers and because of that it doesn't look like a conversation with a real person. Is it possible to adjust settings so that in one conversation it doesn't use the same phrase twice?

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140756353/acf6a33d-1c68-43a5-a3ad-4346d5b818c7)

**Comment by oksana-mlynska** [comment]
@Nanaier and also it's a question can we adjust settings so that it doesn't write 'hello' or 'hi' in the middle of a conversation, It looks strange and happened a couple of times.

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140756353/748941bf-fd69-4643-965e-ba178c1b91b7)

**Comment by Nanaier** [comment]
@oksana-mlynska - will try and work on this, I'll let you know the results tomorrow

**Comment by Nanaier** [comment]
@oksana-mlynska - regarding the first question: will it be okay if the chatbot thinks his name is Doctor Freud.ai? About the second - I changed the prompt to` 'offer a short, compassionate and unique answer to the patient`s question'` so it should generate +- unique answers, but you shall test it yourself. About the third - I'm not sure we can adjust that tho I reproduced your dialog about traveling and it gave me no answer starting with hello

**Comment by oksana-mlynska** [comment]
@Nanaier Thanks, I think Doctor Freud.ai is ok, as this is the name on the chat also.

**Comment by oksana-mlynska** [comment]
@Nanaier it still gives similar phrases in the responses, but I suppose it's not that critical

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140756353/e79cc2e8-bd9b-4831-bfe2-52ab46006b9c)

**Comment by oksana-mlynska** [comment]
@Nanaier things with 'hello' also happen, it's hard to reproduce as it happen suddenly. But again if we can't influece on it, let's leave it as it is.

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140756353/2e6b74e1-6581-4b63-a3c1-621592d8db33)

**Comment by Nanaier** [comment]
@oksana-mlynska - I understand what you mean, the reason for these answers lies in the way the openAi model is taught - from the info that I acquired Chat GPT doesn't possess the intelligence to generate absolutely unique answers and we can't just outright tell the model not to say hi. I think It can be improved in the future using [Fine-tuning](https://platform.openai.com/docs/guides/fine-tuning/fine-tuning) feature - but it is a long process.
