### ISSUE TITLE
Add and edit journal note functionality

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2023-calmpal#194]
- [x] when user clicks on plus button in the sidebar, note should be added
- [x] when user clicks on note item in sidebar, this note should be loaded
- [x] implement view for the notes, should be editable area (you can use contenteditable for this)
     - title - first row 
     - content - everything after 
- [x] content should be saved to backend automatically with debounce - in two seconds after user stops typing 
    - check if there are some other cases like page reload that we should handle
- [x] all user input data should be sanitized from both sides - backend and frontend

depends on Journal functionality #157 

Note: from functionality perspective should be something similar to apple notes

<img width="499" alt="Screenshot 2023-09-03 at 16 38 43" src="https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/64521658/0220837e-52cb-4f60-b13e-9bcea210ec19">

**Comment by OlenaYatseniuk** [comment]
Hey, @Liza-Veis! Could you, please answer on this questions:

1. Can we use EncryptService that we already have in the backend to encrypt data? Or we should use another library for this? if so, should we move it to shared?
2. Can you, please, help me with sanitizing in the backend? I did research and understood that I need to prevent SQL injections, but I don't understand how I could do it, with what libs.
3. Should I limit somehow title and text?
4. What should I do in case page reloads? Do I need to have listeners, and before the page reloads sent it to backend? or temporary save to localStorage when typing?

**Comment by liza-veis** [comment]
Hey! 
1. small update, we decided to make the whole database data encrypted instead of custom encryption, so no encryption needed here
2. as we using orm to insert values and not pure queries, we can only handle html, you can use sanitize-html lib
3. yes, let's limit title to 400 chars
4. let's add listeners

**Comment by OlenaYatseniuk** [comment]
Some clarification, please :
1. It's interesting. It will be another task for doing encryption? Can you remove this requirement from my issue,please?
2. I use this lib for frontend. Should I dublicate the logic for backend or it will be enough from frontend?
3. Should I make migration for this? Or handle it via frontend?

**Comment by liza-veis** [comment]
1. this needs to be done on aws side, just enable one checkbox. Removed it from the requirements
2. we need this lib and helper in shared, and we need to sanitize input on both sides - frontend and backend
3. this should be restricted in database (if we don't have it yet), and in validation-schema

**Comment by OlenaYatseniuk** [comment]
Got it. Thanks!

**Comment by KrychkovskaVira** [comment]
hi @OlenaYatseniuk were there any reasons to reduce 'limit title to 400 chars' to 255, as it is now? 

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/88768615/a5a065c3-4ce9-416a-9af3-5336a746ffe5)

**Comment by KrychkovskaVira** [comment]
@OlenaYatseniuk @HIMDanny 
Furthermore, the following corrections are needed:
1. Selected field should be highlighted
2. List of meditations should be sorted by date, not alphabetically

**Comment by OlenaYatseniuk** [comment]
@KrychkovskaVira I used a db that already was created, so there was a limit for the title to 255. I think we don't need to change it, as it will be enough for title. But we need to ask @Liza-Veis for that.

**Comment by OlenaYatseniuk** [comment]
@KrychkovskaVira Also, what do you mean here: "List of meditations should be sorted by date, not alphabetically", because now we don't have a search for notes at all?

**Comment by OlenaYatseniuk** [comment]
> @KrychkovskaVira I used a db that already was created, so there was a limit for the title to 255. I think we don't need to change it, as it will be enough for title. But we need to ask @Liza-Veis for that.

**Comment by KrychkovskaVira** [comment]
@OlenaYatseniuk 
1. I am testing this task, and I found a [comment ](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/issues/194#issuecomment-1714489029) from Liza that mentions limiting the title to 400 characters. The task also references [#157](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/issues/157), where the description states that the title should be varchar 300. If the title doesn't meet the specified criteria, it is a bug that needs to be fixed or the requirements should be updated
@Nanaier maybe I missed something, and the requirements have changed? I'm just trying to figure out where the limitation of 255 characters came from.

2. My bad, I made a typo: the list of notes should be sorted from newest to oldest. Currently, new notes are being added somewhat strangely. Here's a video recording: 

https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/88768615/9fa6a15c-d311-4559-b8d0-4f0e6c044c45

3. One more bug: in the Google Chrome browser, when you select a note and refresh the page, the note is moved to the first position

**Comment by OlenaYatseniuk** [comment]
@KrychkovskaVira  Thanks for the video. I'll try to fix this.

**Comment by OlenaYatseniuk** [comment]
@KrychkovskaVira Hello! I fixed these issues, so you could test it again. I hope, now everything looks OK.

**Comment by KrychkovskaVira** [comment]
@OlenaYatseniuk 
1. in the Google Chrome browser, when you select a note and refresh the page, the note is moved to the first position - fixed
2. limit title to 300 chars (according to @Liza-Veis comment) - fixed
3. selected field should be highlighted - fixed
4. list of notes should be sorted from newest to oldest - new chats are displayed second in the list until you click on them or refresh the page, attachment: 

https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/88768615/83bac38a-6668-4113-9247-c1f643e345a7

**Comment by OlenaYatseniuk** [comment]
@KrychkovskaVira Thanks, for the feedback. Will try to fix it.

**Comment by OlenaYatseniuk** [comment]
@KrychkovskaVira Can you, please, look at this video and tell me if it looks good now?
Now, if we update the note it jumps to the beginning, and if we try to update and quickly create a new one, so when the previous updates (it has a delay of 2 seconds as a requirement) we can see it in the top too.

https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/102380564/921c1ccf-95cb-4dab-82de-921d3db5442c

**Comment by KrychkovskaVira** [comment]
@OlenaYatseniuk Everything looks great in the video!

**Comment by OlenaYatseniuk** [comment]
@KrychkovskaVira Thanks, so I will notify you when this fix will be merged.

**Comment by OlenaYatseniuk** [comment]
@KrychkovskaVira Hello! These fixes were merged! So you can test it again.

**Comment by KrychkovskaVira** [comment]
Everything is working fine now, thank you!
