### ISSUE TITLE
Add profile button to the sidebar

### ISSUE THREAD

**Issue by KrychkovskaVira** [BinaryStudioAcademy/bsa-2023-calmpal#195]
- [ ] Add the profile button on the sidebar that will navigate the user to the Profile's page

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/88768615/8d296c08-5309-42aa-8bb2-376a7b86fdc0)

**Comment by Ekit18** [comment]
@KrychkovskaVira @Liza-Veis said to change it to home

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/92929504/0e58129f-0e40-4334-b0fd-0f1b362a6598)

**Comment by KrychkovskaVira** [comment]
Alright, based on this information, I'll close the ticket. Thank you!
