### ISSUE TITLE
Add user profile info to home screen

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2023-calmpal#196]
- [x] Add user profile info to home tab 
- [x] Rename Root or Home component to Dashboard (but title should still show home)
- [x] User name should be taken from authenticated user
- [x] Add placeholder image instead of avatar
- [x] User should get to this page when he opens home item

![Dashboard](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/64521658/3041db06-9ce0-49b4-afbb-746c2118fc88)

**Comment by iamAlinaaa** [comment]
@Liza-Veis could you please clarify about Add user profile info to home tab? Does it mean i should add user icon to bottom tab near home or should i add it like here
![Снимок экрана 2023-09-02 191653](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/111873795/2a44359f-c3da-4246-a0bb-ebe76a2065e9)

**Comment by iamAlinaaa** [comment]
for now i have it like this . should i change smth ?
![Снимок экрана 2023-09-06 144109](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/111873795/fec33601-cdec-443e-93e0-2b9eb4039727)

**Comment by liza-veis** [comment]
yes, this icon should be shown on all screens from bottom tab navigation at the header as on chat screen
