### ISSUE TITLE
Loader component

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2023-calmpal#20]
- [x] Add common loader component

**Comment by ossavemu** [comment]
The Loading component was created to show a complete screen with an animated component with css in a loop. The loader.tsx and loader.scss files were created. Added loader to the style index.

**Comment by ossavemu** [comment]
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/90299049/09700fe0-6a79-46bf-af5f-e76538bd64f0)
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/90299049/de7a8b6b-b32f-416f-a70b-f5c26f18a698)
