### ISSUE TITLE
Update swagger documentation for auth/sign-up/survey

### ISSUE THREAD

**Issue by KrychkovskaVira** [BinaryStudioAcademy/bsa-2023-calmpal#203]
- [x]  Add to responses description for 422 Unprocessable Entity for survey request when string data is sent, one of the fields is missed in the body request or body is missed in the request

**Comment by KrychkovskaVira** [comment]
@Dmytro-Kucherenko could you please add this code and description to responses in Swagger?

**Comment by dmytro-kucherenko** [comment]
@KrychkovskaVira  Do you mean in every response, which has body validation?

**Comment by KrychkovskaVira** [comment]
Maybe not every example, but at least one of them.
@Liza-Veis what do you think?

**Comment by dmytro-kucherenko** [comment]
@KrychkovskaVira Just this issue was about adding description for 422 Unprocessable Entity in survey in swagger, I'm trying to understand now what the other responses are you talking about)

**Comment by KrychkovskaVira** [comment]
@Dmytro-Kucherenko I mean, right now there's only one response example; I think we should also add 422
@Liza-Veis what do you think?

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/88768615/78ee1954-f52e-4425-8119-3910a78b1254)

**Comment by liza-veis** [comment]
yes, we need to add it

**Comment by dmytro-kucherenko** [comment]
@KrychkovskaVira Maybe smth is missed, but I can see 422 response. I checked it both on the branch of this issue and on the development branch

![image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/92298163/fc675505-a26c-45d4-bbca-8f0aada5f1b3)
