### ISSUE TITLE
Change Success notifications style

### ISSUE THREAD

**Issue by k-mlch** [BinaryStudioAcademy/bsa-2023-calmpal#212]
Make style of success notifications with rounded corners and with green check button on it

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140718705/e74299bc-e028-4a97-8a7f-9ae106e512ab)

**Comment by oksana-mlynska** [comment]
@Liza-Veis is it possible to check this ticket? There is no such functionality on staging like to add meditation

**Comment by liza-veis** [comment]
Yes, you are right, will assign this to me for a while

**Comment by oksana-mlynska** [comment]
@Liza-Veis the same about this ticket https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/issues/217
