### ISSUE TITLE
Change Success notifications style for mobile app

### ISSUE THREAD

**Issue by k-mlch** [BinaryStudioAcademy/bsa-2023-calmpal#217]
Make the style of success notifications green 

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140718705/4d883d33-a8ae-491f-b010-b09bb6bf4fb7)

**Comment by oksana-mlynska** [comment]
@Liza-Veis I think we can't test this as there is no way we can see success notifications in mobile app now

**Comment by k-mlch** [comment]
currently, the success notifications on the mobile look like this and it's expected behavior so i close this ticket

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140718705/da07c529-8ba9-4d14-a174-6aafac195949)
