### ISSUE TITLE
Improve sidebars

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2023-calmpal#223]
We have two sidebars in our application that are common across all pages. For now we have different implementations of the second sidebar for each page and it's not responsive. 

- [x] rename current Sidebar component to NavigationMenu
- [x] create a common Sidebar component (for the second sidebar) and add it to all pages

responsiveness:

- [x] when user clicks on navigation item in the hamburger menu, they should get to this sidebar (it should take the whole space except header)
- [x] when user clicks on item in this sidebar, it should be closed and user should see appropriate screen
- [x] there should be a way to return back to this sidebar, maybe something like back button on mobile
- [x] should look well on all devices (desktop, tablet, mobile)

Note: All of the criteria above were written as suggestions with no specific vision for how it would be, so ideas are welcome

![Meditation   Breathing](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/64521658/81476758-a241-4a5d-ad82-7f856457e4cb)

**Comment by Ekit18** [comment]
@Liza-Veis this task is about chat-sidebar and meditation sidebar?

**Comment by liza-veis** [comment]
For all pages that we already have, journal too

**Comment by Ekit18** [comment]
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/92929504/1ea49e1c-87d0-46c5-81e3-f266489feebf)

@Liza-Veis is it looks ok?

**Comment by liza-veis** [comment]
Yes, looks good

**Comment by Ekit18** [comment]
@Liza-Veis is it bag if i can open dropdown menu clicking only on dashes? and i can't redirect to another page clicking on item. only clicking on text redirect me. so if it`s a bag can i fix it in this task?

https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/92929504/94e1cc4e-d0bb-413f-a632-4748720d117e

**Comment by liza-veis** [comment]
Yes, this should be fixed

**Comment by Ekit18** [comment]
ok

**Comment by Ekit18** [comment]
@Liza-Veis is it looks good? and if yes should i do the same for other pages, which has only sidebar?

https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/92929504/0b204993-b229-42f8-ac07-51dd3e0b7134

**Comment by liza-veis** [comment]
Yes, looks good and we should do the same for other pages

**Comment by oksana-mlynska** [comment]
While testing this issue also hover effect over sidebar options and active state of the 'search' field should be checked.

**Comment by Ekit18** [comment]
deleted

**Comment by Ekit18** [comment]
deleted

**Comment by k-mlch** [comment]
this whole logic for sidebars doesn't work in Safari browser and will be fixed as part of [this ticket ](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/issues/133)

**Comment by k-mlch** [comment]
sidebar in Safari works fine starting from the 16.6 version (the latest version)
