### ISSUE TITLE
Fix the padding of the journal entries

### ISSUE THREAD

**Issue by k-mlch** [BinaryStudioAcademy/bsa-2023-calmpal#233]
- [x] Fix the padding of the journal entries

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140718705/517f7d31-e58f-4dc2-8316-c97e20755082)

**Comment by KrychkovskaVira** [comment]
@Nanaier could you please confirm example 'Minecraft' note wasn't deleted from journal page?

**Comment by Nanaier** [comment]
@KrychkovskaVira yes, you can still see the "Minecraft" example on the journal page in the deployment

**Comment by KrychkovskaVira** [comment]
@Nanaier Please note that the Minecraft notepad does not appear in the local environment. Could you please fix it?
**Screenshot:**

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/88768615/145742d8-82cd-4c33-847c-017eacaaa108)

**Comment by Nanaier** [comment]
@KrychkovskaVira you are testing in the local environment, if you want to see minecraft entry - you would need to test on the deployment
