### ISSUE TITLE
Add journal notes loading 

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2023-calmpal#234]
- [ ] When user opens journal item in tabs load list of all journal_entries, and display them, styles are the same as for chat list

**Comment by k-mlch** [comment]
@danilittaa is it expected that when i click on 'Add new meditation button' the app crashes and closes? (i don't have such behavior with add new chat button)

**Comment by danilittaa** [comment]
@k-mlch, I think it's absolutely normal because we don't have the implementation of adding a new meditation yet
