### ISSUE TITLE
Consistent headers across all pages: matching the Figma design templates

### ISSUE THREAD

**Issue by KrychkovskaVira** [BinaryStudioAcademy/bsa-2023-calmpal#237]
**Actual design:**

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/88768615/6a65db83-dfce-4f89-92d5-1aa05d0c652f)
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/88768615/b7ca96f2-0420-4bc3-b40e-2464dbe44c95)
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/88768615/1079459e-d5e5-4db9-bf67-ac90edac9518)
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/88768615/407b1a72-2e78-4423-9ff4-dd1188338087)

**Expected design:**

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/88768615/6bed3f78-7ae7-4b63-9a7a-d53e4b2027a5)
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/88768615/fffef8dd-5dfe-4c32-a5db-b87fa784fb06)
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/88768615/82e69ffc-2baf-4f7a-af16-d02c5964d011)

**Comment by Ekit18** [comment]
@Liza-Veis isn`t it my task https://github.com/orgs/BinaryStudioAcademy/projects/12/views/1?sliceBy%5Bvalue%5D=Ekit18&pane=issue&itemId=38010222?

**Comment by liza-veis** [comment]
yes, close it as it will be fixed in #223
