### ISSUE TITLE
[BUG] Images on the list's buttons don't align properly

### ISSUE THREAD

**Issue by k-mlch** [BinaryStudioAcademy/bsa-2023-calmpal#245]
**Description:**
Images on the list's buttons aren't aligned properly

**Steps To Reproduce:**
1. Navigate to the pages where lists buttons with images are present (Chat, Meditation)

**Environment:**
http://calmpal-alb-development-453467742.eu-west-1.elb.amazonaws.com/

**Visual Proof (screenshots, videos, text):**
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140718705/a698d348-d9d3-45a4-be67-571efe90f9cb)
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140718705/d59a6d43-0b0d-4141-844c-91df01d91f95)

**Comment by juanc-escobar** [comment]
they seem to be working here: https://development.app.calmpal.com/chats

![image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/107894952/1583ee72-34d4-4517-8143-cc78d7724e57)

**Comment by juanc-escobar** [comment]
check it out and let me know if we still need to work on it.

**Comment by k-mlch** [comment]
@juanc-escobar looks like it was fixed already, i will close the ticket then

**Comment by k-mlch** [comment]
Closed because bug doesn't reproduce anymore
