### ISSUE TITLE
[BUG] White circles around sidebar options don't have all the same size

### ISSUE THREAD

**Issue by k-mlch** [BinaryStudioAcademy/bsa-2023-calmpal#246]
**Description:**
White circles around sidebar options don't have all the same size 

**Environment:**
http://calmpal-alb-development-453467742.eu-west-1.elb.amazonaws.com/

**Steps to reproduce:**

1. Navigate to the side bar
2. Select each option (Chat, Meditations, Journal, Home)

**Expected Result:**
The white circles around each option are the same size and centered the same way

**Expected Result:**
They have different sizes

**Visual Proof (screenshots, videos, text):**

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140718705/704ab949-5345-49ab-b95e-952413363012)

**Comment by juanc-escobar** [comment]
they seem to work here: https://development.app.calmpal.com/meditation

![image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/107894952/6d1b9517-767b-4b8b-adf7-c65cdc023f4f)

**Comment by juanc-escobar** [comment]
check it out and let me know if we still need to work on it.

**Comment by k-mlch** [comment]
@juanc-escobar yes, i still can reproduce it, the height (also some have different width too) of the white circles around each icon is different and they all should be consistent
<img width="571" alt="Screenshot 2023-09-13 at 10 30 50" src="https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140718705/2f63879e-af27-488b-add4-52f825e66eb1">
<img width="135" alt="Screenshot 2023-09-13 at 10 30 40" src="https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140718705/04a70b6c-eb0c-405e-8043-bb338f83297b">

**Comment by juanc-escobar** [comment]
Hi @k-mlch  can you explain to me how do you get the horizontal view:

![image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/107894952/7ba1e4aa-5b66-41c6-99ba-035df3fd4a30)


I have tried reducing the height and width but the icons either are vertical or disappear.

**Comment by k-mlch** [comment]
@juanc-escobar i made it manually just to compare their sizes and to show it visibly that they're different, i took screenshots and compared circles in figma 🙈

**Comment by KrychkovskaVira** [comment]
Hi @juanc-escobar! Could you please make the chat icon a bit smaller and the my profile icon a bit larger? 

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/88768615/b8d11237-7628-4c49-9d19-41db7f52874b)

**Comment by juanc-escobar** [comment]
@KrychkovskaVira  sure it can be done. @Liza-Veis  should I create a new PR for this?

**Comment by liza-veis** [comment]
yes, let's do it in another pr

**Comment by KrychkovskaVira** [comment]
@juanc-escobar here is additional screenshots: 

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/88768615/c961806c-80e7-4f62-bfd5-dca3ea45e0dd)

**Comment by KrychkovskaVira** [comment]
Hello @juanc-escobar , shouldn't this ticket be in the "To Be Tested" column? Because I can visually see that the icons look the same now.

**Comment by juanc-escobar** [comment]
Hi, @KrychkovskaVira you are right, I just moved it, but I'm in a different time frame this was approved while I was sleeping.

**Comment by KrychkovskaVira** [comment]
@juanc-escobar Yes, you're right, I apologize.
