### ISSUE TITLE
Reduce the height of the navigation bar on the mobile app

### ISSUE THREAD

**Issue by k-mlch** [BinaryStudioAcademy/bsa-2023-calmpal#252]
For now the navigation bar on the mobile app takes too much space, it would be nice to reduce the height of the nav bar 

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140718705/23329aee-1788-43b2-bd18-4c5be7fd753e)

**Comment by oksana-mlynska** [comment]
It looks ok on my device now

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140756353/a7364407-bf11-4f1a-8d8c-6437769304e9)
