### ISSUE TITLE
Loader component

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2023-calmpal#26]
- [ ] Add common loader component

**Comment by Vika030718** [comment]
To QA team: Steps For Testing this Task


1. Open a file with any screen in your code editor, for example, this one: /mobile/src/screens/auth/components/sign-in-form/sign-in-form.tsx
2. Add this line on the top of the file: import { Loader } from '#libs/components/components';
3. Commit everything that is situated in the return statement
4. Add this line to the return statement: <Loader />. Your code now should be like on the screen below.
5. Save the file
6. Open the mobile app and go to the screen from step 1 (sign-in page in our case)
7. Check the loader is being displayed: 

**Code for testing**
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/4521937/59253872-72a8-4018-9c24-a23fba16ba64)

**The result**
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/4521937/6d1d6dc9-0aea-4f8e-8104-874c8f6edd25)
