### ISSUE TITLE
[BUG] 'Add new chat/meditation' button doesn't align properly on mobile app

### ISSUE THREAD

**Issue by k-mlch** [BinaryStudioAcademy/bsa-2023-calmpal#267]
**Description:**
'Add new chat/meditation' button doesn't align properly on mobile

**Environment:**
Mobile CalmPal app

**Steps to reproduce:**

1. Navigate to chat screen/meditations screen

**Actual Result:**

1. The button is not centered on the screen and the plus icon and text don't align properly

**Expected Result:**

1. The button should be centered on the screen and the plus icon and text should be aligned properly as in figma mockup

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140718705/e0a4e8a0-15c3-47a8-aec7-72f207a2d638)

**Visual Proof (screenshots, videos, text):**
Actual:

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140718705/2baaee35-eef0-48c1-9b73-af034ad4ff2e)
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140718705/b699d683-d6a5-40bc-a218-fc4fbd775385)

**Comment by oksana-mlynska** [comment]
@danilittaa I don't know if it is critical, but it seems that the '+' is still not in the center


![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140756353/4807b676-7dc2-4779-8643-ff8043e41841)

**Comment by danilittaa** [comment]
@oksana-mlynska , Hello) In my new task, I completely changed that component (from a link to a button), so now it all looks great. Here's a screenshot: 

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/108797614/541f6507-5b82-458c-a222-c59bdeae1323)

**Comment by oksana-mlynska** [comment]
@danilittaa in the app on the real device I don't see it as on the screen you shared. I assume that the latest version has not been deployed to the Play market yet. So let's wait then.

**Comment by danilittaa** [comment]
@oksana-mlynska , No, it's because this task is not finished yet. I will let you know when it's merged)
