### ISSUE TITLE
Delete chat functionality

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2023-calmpal#268]
<img width="254" alt="Screenshot 2023-09-13 at 16 14 25" src="https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/64521658/01a47a40-b698-4a66-b4cf-6ff4e830ec24">

**User Story:**
As a user, I want to be able to delete individual chats, so that I can organize my chat history and remove conversations that are no longer relevant or necessary.

**Acceptance Criteria:**
- On each chat item, a small "delete" icon (a trash can) should be displayed
- When the user hovers over the "delete" icon (a trash can) it should be highlighted
- When the delete icon is clicked, a confirmation modal should appear to ensure the user's intent
- The modal should have a clear title, such as "Delete Chat?" 
- The modal should have two buttons: "Cancel" and "Delete"
- When the user clicks the "Cancel" button in the modal, the modal should be dismissed, and no further action should be taken
- After the user clicks the "Delete" button in the modal, the chat associated with the delete icon should be removed from the user's chat list

**Comment by OlenaYatseniuk** [comment]
@Liza-Veis  Hey! Should I implement soft or hard delete for this purpose?

**Comment by OlenaYatseniuk** [comment]
@Liza-Veis Do I need to add migration to add user_id column to chats table to check in service delete method whether userId equal chat.userId or can go without it?

**Comment by Liza-Veis** [comment]
You can go without it

**Comment by liza-veis** [comment]
Yes, you need to check this, don't we already have users_to_chats table? You should use it instead of user_id column
