### ISSUE TITLE
Implement chat messaging functionality

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2023-calmpal#270]
Connect chat to the backend on mobile

**User story:**
As a user, I want to be able to send messages in chat and receive answers, so that I can discuss my issues with the virtual therapist.

**Acceptance criteria:**
- A new chat window should be opened when the user clicks on the 'Add chat' icon
- User should be able to type and send a message with the help of the input field
- The sent message should be displayed on the chat page
- User should receive a reply form AI each time he sends a message

**Comment by k-mlch** [comment]
@danilittaa Somehow after the latest update i can't see messages in chat anymore, can u check it, please? 

https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140718705/3ba13873-2bf7-440d-a2de-22ff7d5eaf32

**Comment by danilittaa** [comment]
@k-mlch , Hi, this is because of the recent changes((( I've already fixed it in another task related to the chat (cp-277: Group Chat Messages By Date). So, for now, all we have to do is wait for it to be merged. I'll let you know when it's ready

**Comment by k-mlch** [comment]
@danilittaa okay, thank you, i will wait then till that ticket will be merged
