### ISSUE TITLE
Make title and image for chat autogenerated

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2023-calmpal#274]
**User Story:**
As a user, I want title and image to be generated automatically so that I can save time and conveniently use this feature
**Acceptance criteria:**
1. Each title and image are generated immediately upon sending first message
2. Ensure that generated images are non-repetitive
3. Generated images are abstract

**Comment by Nanaier** [comment]
@Liza-Veis since the messaging functionality is not yet ready + as I can see we haven't yet connected frontend message creation to the backend - can I use the mock message to generate the chat name and image?

**Comment by liza-veis** [comment]
@Nanaier we send the first message with the chat creation request

**Comment by Nanaier** [comment]
@Liza-Veis do you want the generated images to be stored in the files table and alter the chat table with file_id? or is there another approach for this?

**Comment by Nanaier** [comment]
or can i just store the URL to S3 in altered media_url column?

**Comment by liza-veis** [comment]
yes, we need to upload them to S3 and add to files table, but save url (not id) to chat table, also let's make column like image_url

**Comment by Nanaier** [comment]
@Liza-Veis - I got the functionality to work tho it takes a couple of tenths seconds to generate the image therefore and chat entity - what should I do in a situation like this?

**Comment by liza-veis** [comment]
even if we change response_format and use small image size? As I see from other tutorials it generates images quite fast, maybe this work this way because of free plan or it's timely issue that will work okey in a couple of hours. If not, then we can have another solution here to send two requests. First one to generate chat and we will use default image and the second request to generate image and add it to chat

**Comment by Nanaier** [comment]
thanks - I'll try to play around with sizes - if that won't help, I'll send 2nd request

**Comment by KrychkovskaVira** [comment]
Hi @Nanaier The generated images appear to be slightly more contrasted and brighter than what is depicted in Figma. Can we replace them with calmer colors?

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/88768615/eee0c979-9145-4cf2-aa06-a161970818f0)

**Comment by Nanaier** [comment]
I think - yes, I can make it work - could you create a ticket for that or would you just move this ticket in to do?

**Comment by Nanaier** [comment]
@KrychkovskaVira will those work for you?

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/90211108/81dbbabc-f202-41a4-a700-158905079b3f)

**Comment by KrychkovskaVira** [comment]
@Nanaier yes, it looks good, thanks

**Comment by KrychkovskaVira** [comment]
@Nanaier could you please notify me once it will be added to stage?

**Comment by Nanaier** [comment]
@KrychkovskaVira it got merged - you can test it now
