### ISSUE TITLE
Group chat messages by date

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2023-calmpal#276]
- [x] Date should be relative

<img width="540" alt="Screenshot 2023-09-13 at 21 18 07" src="https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/64521658/8ac7a547-9c2c-4956-bb29-c66002a820b3">

**User Story:**
As a user, I want messages in the chat to be visually separated by their relative date, so that I can easily distinguish between messages sent today, messages sent yesterday, and older messages.

**Acceptance criteria:**
- Messages in the chat must be visually separated based on their relative date
- Relative dates should include "Today," "Yesterday," and the actual date for older messages
- When the user scrolls through the chat history, the relative date separation should remain consistent

**Comment by dmytro-kucherenko** [comment]
@Liza-Veis Will the similar functionality be implemented on mobile?

**Comment by liza-veis** [comment]
Yes

**Comment by KrychkovskaVira** [comment]
hi @Dmytro-Kucherenko could you please add 'Yesterday' date? 

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/88768615/e72c5f63-a7fc-4f00-90ec-2d0f73434ca1)
