### ISSUE TITLE
When 401 error occurs, signout user from the app

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2023-calmpal#291]
Note: you can test it by deleting token of authorized user from local storage

**Comment by oksana-mlynska** [comment]
@OlesiaTr now it worsk only for menu options Journal and Chat. Could you please check if I am testing correctly



https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140756353/1a1beee2-0408-4e58-990b-5529336097ce

**Comment by OlesiaTr** [comment]
@oksana-mlynska because Chats and Journal are the only pages right now, that are making requests to the backend. So you are doing it correctly, don't worry.

**Comment by oksana-mlynska** [comment]
@OlesiaTr then I guess the task is implemented and I can close it
