### ISSUE TITLE
Delete note functionality

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2023-calmpal#295]
- [x] user should be able to delete note, by clicking trash icon
- [x] add confirmation modal before deletion

<img width="254" alt="Screenshot 2023-09-13 at 16 14 25" src="https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/64521658/3a3bf761-57f8-459b-9336-f563099b7d0f">

**User Story:**
As a user, I want to be able to delete notes, so that I can organize my journal history and remove notes that are no longer relevant or necessary.

**Acceptance Criteria:**

- On each note card, a small "delete" icon (a trash can) should be displayed
- When the user hovers over the "delete" icon (a trash can) it should be highlighted
- When the delete icon is clicked, a confirmation modal should appear to ensure the user's intent
- The modal should have a clear title, such as "Delete Note?"
- The modal should have two buttons: "Cancel" and "Delete"
- When the user clicks the "Cancel" button in the modal, the modal should be dismissed, and no further action should be taken
- After the user clicks the "Delete" button in the modal, the note associated with the delete icon should be removed from the user's notes list

**Comment by Ekit18** [comment]
@Liza-Veis i have one question: is it a bug if in journal entry schema we don`t have userId or smth related to user?

**Comment by Ekit18** [comment]
@Liza-Veis and also one question: can i add to card prop smth like:
isTrashBucket: boolean
?

**Comment by liza-veis** [comment]
@Ekit18 
> i have one question: is it a bug if in journal entry schema we don`t have userId or smth related to user?

yes, this is a bug, I think it would be fixed in #293 

> and also one question: can i add to card prop smth like:
isTrashBucket: boolean
?

let's add property iconRight and onIconClick

**Comment by Ekit18** [comment]
@Liza-Veis i've just find a little bug. if we have a big text in sidebar card title it can break card view like this:


![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/92929504/88c2cce8-7f63-49c0-9860-93155534615f)

can i fix it in this task adding text-oveflow elipsis?

**Comment by Ekit18** [comment]
And also should i copy modal from [here](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/pull/213)?

**Comment by liza-veis** [comment]
1. No, ask qa to create another ticket for the issue above
2. Yes, you can copy it from there

**Comment by Ekit18** [comment]
@Liza-Veis Should i add this trash icon as a button? And if yes, i have another problem: i can`t make button child of the button(our card element is button). So if i place this trash icon with position relative will it be ok?

**Comment by liza-veis** [comment]
yes, it's should be a button

> So if i place this trash icon with position relative will it be ok?

yes

**Comment by k-mlch** [comment]
@Ekit18 is this functionality already added to [the development ](https://development.app.calmpal.com/)? for now, i don't see a delete button for any of my note cards

**Comment by k-mlch** [comment]
okay, don't mind previous message it's appeared now
