### ISSUE TITLE
Delete note functionality

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2023-calmpal#296]
<img width="254" alt="Screenshot 2023-09-13 at 16 14 25" src="https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/64521658/3a3bf761-57f8-459b-9336-f563099b7d0f">

**User Story:**
As a user, I want to be able to delete notes, so that I can organize my journal history and remove notes that are no longer relevant or necessary.

**Acceptance Criteria:**

- When the user swipes left on the note item, a "delete" icon should appear on the right-hand side of the container
- After the user taps the "delete" icon, a confirmation modal should immediately appear
- The modal should have a clear title, such as "Delete Note?"
- The modal should have two buttons: "Cancel" and "Delete"
- When the user clicks the "Cancel" button in the modal, the modal should be dismissed, and no further action should be taken
- After the user clicks the "Delete" button in the modal, the note associated with the delete icon should be removed from the user's note list

**Comment by oksana-mlynska** [comment]
@iamAlinaaa 
I think that a note should go back to the initial state if I slided for deletion, didn't delete and switched to other fields.
But I think this should be created in a separate issue as improvement

https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140756353/17e3c140-9b2d-42ea-b9ed-1e05a88f822d
