### ISSUE TITLE
Fix sidebar redirect

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2023-calmpal#300]
When `?sidebarMode=hide` is not present in the url, sidebar should be hidden.

Note: this shouldn't broke the logic with sidebar navigation

**Comment by HIMDanny** [comment]
@Liza-Veis, I have an idea, please tell me if it is a good one. First, we change the behavior of the sidebar and show it only on `?sidebarMode=show`. 
Then we create a helper like `getLinkWithSidebarShow` and use it in sidebar routes. 
Or even we can create a generic helper for URL params and use like:
```ts
const linkWithParams = createLinkWithParams({
  sidebarMode: 'show'
})

const ROUTES = [
  {
    path: linkWithParams(AppRoute.CHATS)
  }
]
```

Does this idea have a life chance?)

**Comment by liza-veis** [comment]
I like your idea, small changes to it:

1. let's have helper like getUrlWithQueryString and use URLSearchParams in it
2. also let's create a enum for common keys, something like AppQueryStringKey and enum for SidebarMode

**Comment by HIMDanny** [comment]
@Liza-Veis, do I need to handle multiple values in one key in searchParams? (ex. `topics=firstTopic,secondTopic`)

**Comment by liza-veis** [comment]
no, not for now

**Comment by KrychkovskaVira** [comment]
@HIMDanny I have several observations:
In Chrome, the scrollbar is not displayed when "sidebarMode=show" is present in the URL. Additionally, the oldest chat does not fit on the screen regardless of the resolution.
Attachment:


![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/88768615/933dae65-9991-4492-b411-eb32ece88250)


In Mozilla, the oldest chat does not fit on the screen regardless of the resolution, which causes the scrollbar to be hidden.
Attachment:


![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/88768615/763ab909-a9c2-465b-9542-86c7b353c2bc)

**Comment by HIMDanny** [comment]
@KrychkovskaVira, I guess it is not a part of my task, because I was working on redirection only and not haven't changed styles. Can we create a ticket for this issue?

**Comment by KrychkovskaVira** [comment]
@HIMDanny thank you for the clarification!
