### ISSUE TITLE
Improvements to Hamburger Menu

### ISSUE THREAD

**Issue by k-mlch** [BinaryStudioAcademy/bsa-2023-calmpal#302]
1. The whole button for each item should be clickable not only line with a text

https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140718705/a21daa44-56ec-494f-9a35-ab40fcec0279

2. Align all the names vertically so that they all start from the same point

Actual: 
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140718705/51fac26f-fcc9-48b9-a5af-d501f0c861fc)

Expected:
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140718705/63aed2eb-d965-410e-9996-865f9f264fbb)

**Comment by oksana-mlynska** [comment]
@OlesiaTr I started to test this ticket and that's what I see now in Chrome


![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140756353/7c8b0fa9-4f6a-48fc-a484-cbd138ff366d)


and in Safari on actual device I don't see icons on the hamburger menu at all



![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140756353/3f5db47e-dfc6-4cab-aaa6-bbbc764b55d6)

**Comment by OlesiaTr** [comment]
@oksana-mlynska for disappeared and big icons we have another issue, you can wait for it to be in the Todo list, so we could work on it https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/issues/317

**Comment by oksana-mlynska** [comment]
@OlesiaTr ok, then I will wait for the fix and then retest the current issue.
