### ISSUE TITLE
Move search for chats and journal notes to the backend part

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2023-calmpal#314]
- [x] we need to move search to the backend part
- [x] handle this using `search` query parameter on frontend
- [x] search should be case insensitive

**Comment by Ekit18** [comment]
@Liza-Veis but we don't have in journal sidebar search field. we have it in meditations

**Comment by liza-veis** [comment]
Let's remove it from meditations and add to journal

**Comment by Ekit18** [comment]
@Liza-Veis should i save it in query parametrs of the page link?

**Comment by liza-veis** [comment]
yes

**Comment by oksana-mlynska** [comment]
@Ekit18 is it an expected behaviour that the request is sent two times?


![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140756353/a898fd1d-a559-4c88-8fa3-43dbb536f8ca)

**Comment by Ekit18** [comment]
@oksana-mlynska is it localhost or prod?

**Comment by oksana-mlynska** [comment]
@Ekit18 on prod 

https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140756353/a71bef1e-2189-4fd2-ab91-386666d18201

**Comment by Ekit18** [comment]
@oksana-mlynska it`s bug but not related to my task. you can see that without any query it will make two requests

**Comment by oksana-mlynska** [comment]
@Ekit18 ok, I'll create a new ticket for that
