### ISSUE TITLE
Modify response body for 'journal' requests

### ISSUE THREAD

**Issue by oksana-mlynska** [BinaryStudioAcademy/bsa-2023-calmpal#315]
- [x] Add userId to 201 response for post/journal request

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140756353/2d9a07f5-ad8a-4503-a36c-ef05763cb8f7)

- [x] Add to swagger documentation response for the case when the length of the title is over the limit (limit is 400 chars)
- [x] Add userId to 200 response for get/journal request

**Comment by oksana-mlynska** [comment]
Also, there's a question: since our journal notes may be edited, maybe we also need some endpoints for put or patch requests? Or maybe it is already planed to be created later.

**Comment by OlenaYatseniuk** [comment]
@oksana-mlynska this will be added when this #293 pr is merged, as I worked there on updating and added userId there too.

**Comment by OlenaYatseniuk** [comment]
So, maybe @Dmytro-Kucherenko you can wait until pr is merged and this issue will be resolved there

**Comment by dmytro-kucherenko** [comment]
The only I need to add is swagger response in case of validation error while creating journal. Everything else @OlenaYatseniuk actually added)

**Comment by oksana-mlynska** [comment]
@Dmytro-Kucherenko in get/journal request in swagger we have responses with 200 status code and 201 with the same description Successful operation. But 201 is usually for creating something and it is a get request, it can't create anything. Is it a mistake?

**Comment by oksana-mlynska** [comment]
@Dmytro-Kucherenko @OlenaYatseniuk Could you check these requests in Swagger, I think there's a mistake in the endpoint

get/journal-entries/{id}
put/journal-entries/{id}

This way requests don't work and return 404 status, but if I remove -entries and use just journal/{id} they work fine.
And on UI I also see that endpoints without word 'entries' are used.

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140756353/319b3647-d603-4016-aa50-4ac787e6d094)

**Comment by oksana-mlynska** [comment]
@Dmytro-Kucherenko @OlenaYatseniuk Also I think it should be journal ID not Chat ID here


![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140756353/dc1b36d9-9a49-4cc4-9c6d-54bae50a3673)

**Comment by OlenaYatseniuk** [comment]
@oksana-mlynska Yes, you are right, these are typos in the swagger documentation. I can fix it. Thanks for noticing.

**Comment by OlenaYatseniuk** [comment]
@oksana-mlynska This was merged, so you can check it.
