### ISSUE TITLE
[BUG] Items in the navigation bar are not highlighted

### ISSUE THREAD

**Issue by k-mlch** [BinaryStudioAcademy/bsa-2023-calmpal#318]
**Description:**
Items in the navigation bar are not highlighted

**Environment:**
Chrome
Safari

**Steps to reproduce:**

1. Open the web app https://development.app.calmpal.com/
2. Click on any item in the nav bar except for the home (Chat, Journal, etc.)

**Actual Result:**
Selected item is not highlighted

**Expected Result:**
Selected item is highlighted

**Visual Proof (screenshots, videos, text):**

https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140718705/6ad4c69a-ac78-4d20-a4d4-f326039a2a9b

**Comment by KrychkovskaVira** [comment]
hi @OlesiaTr the bug is fixed in Google Chrome, but it still reproduces in Mozilla Firefox, could you please fix it?
