### ISSUE TITLE
Header Component

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2023-calmpal#32]
- [x] Add header component
- [x] Replace Log In with Sign In
- [x] Sign In link should navigate to Sign In screen
- [x] Add header to main screen

Use attached logo

![Logo](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/64521658/de22e05f-0d43-48f2-886d-ddbec736e6ef)

![Sign up](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/64521658/d8053020-34cc-4e73-aad7-acc29c500110)

User Story: 
    As a user,
    I want to easily recognize the brand and access the sign-in option,
    So that I can quickly identify the site and sign in to my account.

Acceptance Criteria:
    1. User should see a header displayed at the top of the main page
    2. User should be able to navigate to the sign-in page via 'Sign In' button

**Comment by ossavemu** [comment]
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/90299049/49e9985f-058e-4c86-a41a-3271b2891bf3)

**Comment by ossavemu** [comment]
Header with navigation bar created. An attempt has been made to follow the styles of the example. For the screenshot, the background of the screen was colored in an auxiliary way, but the white background was kept.

**Comment by ossavemu** [comment]
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/90299049/26610603-f41c-47e8-a281-807ed440bebf)
