### ISSUE TITLE
Improve item creation buttons

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2023-calmpal#329]
The problem with the current design is that user needs to scroll to the bottom of the list to create a new item.
To fix this problem there are two solutions for us:
- move button to the top of the list
   will take screen space
- add something like usual floating button
  harder to implement, we need to make it look good with the bottom tabs 

- [ ] choose the best solution for user experience
- [ ] this should be fixed for all places where we have such buttons

<img width="334" alt="Screenshot 2023-09-20 at 01 07 11" src="https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/64521658/f2933d19-e2a5-4c3e-867e-11855d9a1b41">

**Comment by BrianSammit** [comment]
@Liza-Veis Does the button need to keep the same design?

**Comment by BrianSammit** [comment]
Hi @Liza-Veis I checked the issue but the button works correctly at the bottom. There is no need to scroll to add a new chat.

![Vídeo sin título ‐ Hecho con Clipchamp](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/64173189/85142da8-8d4b-430b-9ffa-5179eefe53c8)

**Comment by liza-veis** [comment]
yes, you are right, then I will close this issue
