### ISSUE TITLE
Improvement scrollbar for chat list on the chat page

### ISSUE THREAD

**Issue by KrychkovskaVira** [BinaryStudioAcademy/bsa-2023-calmpal#334]
1. In Chrome, the scrollbar is not displayed when "sidebarMode=show" is present in the URL. Additionally, the oldest chat does not fit on the screen regardless of the resolution.
Attachment:

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/88768615/fedf367b-e39d-4460-911a-a54e57e4bba7)

2. In Mozilla, the oldest chat does not fit on the screen regardless of the resolution, which causes the scrollbar to be hidden.
Attachment:

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/88768615/c242bd1c-289e-4736-93a7-7b75b02a1013)

**Comment by OlesiaTr** [comment]
@KrychkovskaVira hey, what exactly do you mean by "doesn't fit regardless of resolution", and are we supposed to have a scrollbar?

**Comment by KrychkovskaVira** [comment]
@OlesiaTr I mean that the oldest chat is not displayed. In the screenshot, you can see that it is on the page below, but it is impossible to scroll to it
Regarding the response about the scrollbar, I'll come back later

**Comment by KrychkovskaVira** [comment]
Hi @OlesiaTr 
I got the answer from PO: there should be a scroll bar

**Comment by OlenaYatseniuk** [comment]
Hi @KrychkovskaVira 
I have already fixed these bugs. So for now we don't have a scrollbar. If we need to add it, will we have a design for it?

**Comment by KrychkovskaVira** [comment]
@OlenaYatseniuk Yes, you're right. I will create another ticket for adding a scrollbar. Thank you!
