### ISSUE TITLE
Lock theme for the app

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2023-calmpal#335]
Currently app theme is not locked and that's why some colors change when we switch device to the dark mode. We need to lock this, so that app always uses a light theme

**Comment by BrianSammit** [comment]
Hi @Liza-Veis  I cannot find any change on the styles when changing my device to dark mode could you provide me with which Android version is this happening?
Also, there are two ways I found how to solve this issue:

1. Changing the native config style in Android and IOS
2. Use Appearance to always be light mode on the app

Which one should I implement?

**Comment by liza-veis** [comment]
you need to modify native configs to set light mode by default on android, as I remember the problem was on sign-in screen that text in inputs becomes invisible

**Comment by BrianSammit** [comment]
ok

**Comment by k-mlch** [comment]
@BrianSammit can u give any tips what is the best way to test this item on my mobile device? is there any way to set custom colors on android?

**Comment by k-mlch** [comment]
@BrianSammit  okay nevermind my comment higher i think i found the way already 😊

**Comment by k-mlch** [comment]
I found one more issue regarding this ticket but created a separate ticket for it: [here it is 455](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/issues/455)
