### ISSUE TITLE
Use fonts from design

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2023-calmpal#336]
- [x] set up and use custom fonts from design 

Note: you can take fonts from frontend part

**Comment by k-mlch** [comment]
@iamAlinaaa 

font of the titles of Chats isn't updated to the font from Figma mockups 

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140718705/474d6eb3-e81d-416d-beac-3fda7ea8f15f)
