### ISSUE TITLE
Make "+" buttons identical on the Chat sidebar and Meditation sidebar

### ISSUE THREAD

**Issue by oksana-mlynska** [BinaryStudioAcademy/bsa-2023-calmpal#337]
Now the size of the "+" buttons on the Chat sidebar and on the Meditation bar are different in size and on the mobile screen they have different location. They should be identical like on figma design

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140756353/0e9ada0b-de6e-43ad-afd3-5dd1d5230a2b)

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140756353/6958a6f4-d720-4c86-b069-2e1ae9bd0075)

**Comment by Xxandder** [comment]
@Liza-Veis Hello, could you pleasem tell is it ok when header title in meditation list takse 2 rows and its height more than in other pages?



![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/111736110/f55d12a7-4c81-41fe-a7ce-7dee4f0bc980)



![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/111736110/baaa8f50-0ee1-4fa0-905e-ee4bb529f250)

**Comment by liza-veis** [comment]
should have the same width

**Comment by Xxandder** [comment]
@Liza-Veis Now they have the same width but different height because title in medidation takes 2 rows. So may I leave it as it is? or I need to disable text wraping? But in this case we need to decrease font size of the title

**Comment by Xxandder** [comment]
And I also have ome more question about realization of this task. On the first screen you see sizes of Journal page header. It's 30 height and 30px top and bottom paddings. But on the task we need to make 33.33 px icons. It will increase height of the block. So may I decrease paddings in chat and meditatiin pages to 26.67px of there is better way to do it?  (the second screen is the sizes of chat and meditation pages headers)



![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/111736110/3b2a170b-e8aa-4e6b-9a3b-8c55f3146a63)


![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/111736110/fc7548fb-4c94-4b58-9c38-a7f981f98a1b)

**Comment by Xxandder** [comment]
I see that there is task with height of headers. May I assign it to myself? I think it's better to seolve them simultaneously because they are related.

https://github.com/orgs/BinaryStudioAcademy/projects/12/views/1?pane=issue&itemId=39427293

**Comment by liza-veis** [comment]
Yes, you can assign yourself

**Comment by liza-veis** [comment]
It's ok to round values, you can use 33. Don't use floating numbers

**Comment by liza-veis** [comment]
It's ok if headers will take different heights in this case

**Comment by KrychkovskaVira** [comment]
@Xxandder With the height, everything looks fine, but the plus button still has different positioning for mobile and tablet devices. It should be placed on the right side, as shown in the Figma design, for mobile devices.
Currently, it looks like this: 

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/88768615/eb4615c5-510d-4e69-9c01-bafdbce708d5)

But it should look like this: 

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/88768615/aedf9400-3992-4a52-9ba6-9f9b88bf2c9b)

**Comment by Xxandder** [comment]
@KrychkovskaVira Do I need to delete burger menu button from all sidebars?

**Comment by KrychkovskaVira** [comment]
No, the burger menu should remain, but the '+' button for all items should be on the right
@Liza-Veis what do you think?

**Comment by Xxandder** [comment]
Done with the location of the icons, created a pr. Will change it in case the burger menu should be deleted

**Comment by KrychkovskaVira** [comment]
Could you let me know if these changes have already been added to staging?

**Comment by KrychkovskaVira** [comment]
Please disregard the previous question, the updates have been added.

**Comment by Xxandder** [comment]
@KrychkovskaVira It's alredy merged so you can test it
