### ISSUE TITLE
Improvements for sidebars on mobile screen size

### ISSUE THREAD

**Issue by oksana-mlynska** [BinaryStudioAcademy/bsa-2023-calmpal#338]
1) I have a suggestion to reduce the space between search field and options of the sidebars on the mobile screen size.
If we look at the design of the mobile app, there's no so much space and it looks much nicer.

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140756353/65177e9f-f4c5-49cc-ad14-3607c01a03ca)

2) On mobile screen size the options on the Meditation sidebar and on the Journal sidebar are centeres, while on Chat sidebar and Profile settings sidebar they are not. They should be all identical.

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140756353/ae081c37-99f6-4dc3-8242-147b134f15cd)

3) On the mobile device (I was testing in Safari browser) when you click on the search field on the Chat sidebar or on the Meditation sidebar, the screen zooms in a little and stays like this even after user finishes the search and it breaks the design of the page.

I think it shouldn't zoom this way

https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140756353/6dd80c9c-0c12-4c1f-9b60-19cde1d39e41

**Comment by liza-veis** [comment]
we will skip the third point for now

**Comment by oksana-mlynska** [comment]
the second point also may be skipped as now options are already centered on the mobile size screen
