### ISSUE TITLE
Stripe integration

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2023-calmpal#347]
- [x] Add stripe integration
- [x] Use screenshot below as a reference but adjust to our app style
- [x] User should get to this screen by clicking subscription button in profile
- [x] We won't have locked features, but for features included in plan add:
     - use chat functionality
     - create custom meditations
     
 Implementation should be similar to this:
 https://github.com/BinaryStudioAcademy/bsa-winter-2022-2023-simpleland/blob/development/backend/src/libs/packages/billing/billing.package.ts
 https://github.com/BinaryStudioAcademy/bsa-winter-2022-2023-simpleland/tree/development/backend/src/packages/subscription
 
 Note: you don't need to block functionality if user have no subscription for now

<img width="375" alt="Screenshot 2023-09-21 at 19 07 58" src="https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/64521658/93f49e9f-2334-46c8-9ec0-185ad2a0e0fe">
<br />
<img width="413" alt="Screenshot 2023-09-21 at 19 10 18" src="https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/64521658/c79e7348-228b-4a91-8927-c161adfe9442">

**Comment by HIMDanny** [comment]
@Liza-Veis, what should happen when the user clicks the subscribe button? Should the user being redirected to the form to fill the info? Or the subscription would be confirmed already after the the subscribe button has been pressed?

**Comment by HIMDanny** [comment]
I also found that the implementation of the integration in the example that you gave is slightly deprecated. Should I proceed with a similar realization anyway, or try to use the suggested way from stripe documentation (PaymentIntents)?

**Comment by liza-veis** [comment]
yes, you can update it, if it was deprecated. When user clicks the subscribe button, he should be redirected to a form to enter his credentials

**Comment by liza-veis** [comment]
Also we have updated design a little, so make it in this style [figma](https://www.figma.com/file/Mwb2NT7u8o9WAvCDVlzylu/My-Subscriptions?type=design&node-id=0%3A1&mode=design&t=zCMmGHZDMX1J7Pkz-1)

<img width="650" alt="Screenshot 2023-09-22 at 16 20 30" src="https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/64521658/4712017e-f9ac-4d1e-9fcc-89d80a089326">

**Comment by HIMDanny** [comment]
sure, I will do this

**Comment by HIMDanny** [comment]
@Liza-Veis, do I need to add an actual subscription integration from stripe, or just one payment for now?

**Comment by liza-veis** [comment]
One payment will be enough
