### ISSUE TITLE
Disable the 'send' button when the input field on the chat page is empty

### ISSUE THREAD

**Issue by KrychkovskaVira** [BinaryStudioAcademy/bsa-2023-calmpal#354]

**Comment by KrychkovskaVira** [comment]
@OlesiaTr Can you please remove the hover effect when the button is disabled? 
If it's time-consuming, I can create a bug for this to close this ticket.



![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/88768615/a0bd7995-2a9b-45e9-95bc-d432be008ba8)

**Comment by OlesiaTr** [comment]
Sure, I can

**Comment by KrychkovskaVira** [comment]
@OlesiaTr could you please notify me once it will be added to stage?

**Comment by OlesiaTr** [comment]
@KrychkovskaVira you can test in now!
