### ISSUE TITLE
[BUG] All existing on the system meditations are displayed on meditation list after reloading the page

### ISSUE THREAD

**Issue by KrychkovskaVira** [BinaryStudioAcademy/bsa-2023-calmpal#359]
**Description:**
All existing on the system meditations are displayed on meditation list after reloading the page

**Preconditions:**
New user is registered

**Steps to reproduce:**

1. Navigate to Meditation & Breathing page
2. Add new meditation
3. Reload the page
4. Pay attention that meditation list displaying all meditations

**Actual Result:**
All existing on the system meditations are displayed on meditation list after reloading the page

**Expected Result:**
Only previously created meditation is displayed on meditation list after reloading the page.

**Visual Proof (screenshots, videos, text):**

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/88768615/985c3279-2021-4666-80a5-57c777764054)

**Severity:**
Major (S2)

**Comment by KrychkovskaVira** [comment]
@Dmytro-Kucherenko could you please double check because the bug is still reproducible

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/88768615/921b6758-b9ac-4ac1-8c8a-2c3a8682464c)

**Comment by dmytro-kucherenko** [comment]
@KrychkovskaVira No, I don't have this problem and it wasn't appear earlier, so I even didn't pay attention
