### ISSUE TITLE
Improvements for a Journal page

### ISSUE THREAD

**Issue by oksana-mlynska** [BinaryStudioAcademy/bsa-2023-calmpal#368]
1) On other sections when we click on them, the first option of the sidebar is active by default and on Chat section we see the page of a new chat. This way the screen is never empty. But on Journal section when we click on it, no option is active by default and on the right side of the screen we see just a huge white space.

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140756353/fc26c420-de4a-4a33-922f-260596e85f25)

It's even worse for the just signed up user. He clicks on the Joirnal section and sees almost blank page

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140756353/e8822a67-b4b2-444f-bfda-c8d821e25001)

Maybe we should make the first note active or like in chat show the page for creating a new note, or some text like: "this is the journal where you can write down your thoughts and feelings".

2) When we click on the '+' button, the new note appears already with the title and text. And to type my own title I need to delete the existing one at first. It's rather inconvenient. Maybe it would be better if a new note is saved only after a user starts typing something. But I don't know if we have time to change this functionality.

https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140756353/de485078-adb9-4d66-8481-36cd4818e012

3) When I edit a note, it goes to the top of the list only after I click on other one. I'm not sure if it's a bug, but it would be logical if it would go to the top at once after updating the name in the list.

https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140756353/834da1e1-cd26-4233-aba9-882765c80130

4) Placeholder 'New note' is not informative. It should make a hint for a user what to type. I suggest that we change it for 'Enter the title" as on Figma design

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140756353/493e8bb3-03d8-4f7e-8513-1299f6779f24)

5) I suggest to remove dropshadows fron the fields in redactor as they are not present in Figma.

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140756353/da94a759-7d9f-4e31-a0f0-723010610b1f)

**Comment by k-mlch** [comment]
Can we also make 'Type your text here' text like a placeholder so that when the user starts to type their own text it should disappear and the user shouldn't delete it manually?

Currently, it works like this: 

https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140718705/4a26e496-8caa-4e24-865f-887593b20007

**Comment by OlenaYatseniuk** [comment]
@oksana-mlynska Hey! About the 3. It will be fixed in #398

**Comment by dmytro-kucherenko** [comment]
@k-mlch Yeah, I'll do placeholders the way you suggested

**Comment by dmytro-kucherenko** [comment]
@oksana-mlynska In the point 5 do you mean to totally remove this drop shadow on focus? Or you're saying about placeholders colors

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/92298163/d7b954ee-d833-4149-9620-6bbf5855082f)

**Comment by oksana-mlynska** [comment]
@Dmytro-Kucherenko I'm sorry for such a late reply. I suggest that we make as other input fields in the app, so that everything will be in one style
without drop shadow

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140756353/af5ea959-c0c5-48cd-a77b-bb10245b8557)

**Comment by oksana-mlynska** [comment]
@Dmytro-Kucherenko you did a great job on this page, now it's much better from a usability point of view. The only thing is that I still see drop shadow on the fields 


![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140756353/25d76d73-5a10-4296-aae9-d89a40c9d02c)
