### ISSUE TITLE
Reduce the font size for 'Already have an account..' caption on Sign in/up pages

### ISSUE THREAD

**Issue by k-mlch** [BinaryStudioAcademy/bsa-2023-calmpal#376]
Since the caption doesn't fit in one line on all mobile devices it would be nice to reduce the font size for the 'Already have an account..' caption on Sign in/up pages

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140718705/fe1f07f7-5e64-4e23-8cd2-9e025b428430)

**Comment by oksana-mlynska** [comment]
@iamAlinaaa I have just updated the app but I still see the caption as on Katya's screenshot. The display on my device is 6.26". @k-mlch Could you check on your device?

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140756353/bc71a39a-76d9-4d22-aec6-c56333f06e8d)

**Comment by k-mlch** [comment]
@oksana-mlynska i believe those changes weren't added to the latest version of app, ask Volodymyr to update please

**Comment by iamAlinaaa** [comment]
@oksana-mlynska yeah, i think the same way as @k-mlch )

**Comment by oksana-mlynska** [comment]
Yes, now it's in one line. Maybe we should center this caption? What do you think @iamAlinaaa @k-mlch 

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140756353/046e7970-f98f-4ce6-bacb-d65a4ef91902)

**Comment by iamAlinaaa** [comment]
@oksana-mlynska i dont think we should do it, because if it will be centered it probably can became two line again on some phones

**Comment by k-mlch** [comment]
@oksana-mlynska i'm not sure, because it seems that this caption is not centered on the figma mock-up and we have all other fields aligned by the left side so maybe it's okay like it is
