### ISSUE TITLE
Bottom Tab Navigation

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2023-calmpal#38]
https://reactnavigation.org/docs/bottom-tab-navigator/

- [x] Add bottom tab navigation (only home item for now)
- [x] For now, we will use gray color for inactive items and blue for active (without circle)

Notes: It's ok that tab will be centered because of one tab

![Group 1171274916 (1)](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/64521658/81f51c92-2832-46e3-be93-2bb53611dc58)

User Story:
As a user, I want to use bottom tab navigation menu so that I can quickly and easily navigate through application features

Acceptance criteria:
1. User should be able to switch between sections with the help of bottom tab navigation menu
2. Active tab should be highlighted so that user could understand which section is now opened

**Comment by oksana-mlynska** [comment]
No possibility to check inactive tabs as there's only one tab for now. Added this check to checklist.
