### ISSUE TITLE
[BUG] The messages in a chat are shown not in a streight order after you navigate to other sections.

### ISSUE THREAD

**Issue by oksana-mlynska** [BinaryStudioAcademy/bsa-2023-calmpal#440]
**Description:**
The messages in a chat are shown not in a streight order after you navigate to other sections and then return to the chat.

**Steps:**

I made a screenshot how the conversation with the bot started

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140756353/bb5b8b43-fb46-4cc2-a141-96283eff7d7f)

After I navigated to other sections of the app and opened this chat again some messages are mixed and provided not in the order they appeared

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140756353/58f846c4-808d-4f15-9ec1-b749864a1615)

**Comment by dmytro-kucherenko** [comment]
@oksana-mlynska I can't reproduce that bug in development, is it still appears? Yesterday pr about grouping chat messages was merged and I think it fixed that problem

**Comment by oksana-mlynska** [comment]
@Dmytro-Kucherenko yes, today in the morning I also noticed that it is not reproduced. Maybe I will do some more testing today and if it's already fixed, then I will close the issue.

**Comment by oksana-mlynska** [comment]
The bug is not reproduced anymore, so I am closing the issue
