### ISSUE TITLE
Improvement: Add a space at the bottom for meditation placeholders

### ISSUE THREAD

**Issue by KrychkovskaVira** [BinaryStudioAcademy/bsa-2023-calmpal#445]
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/88768615/97e90410-bbd4-4ecb-8609-4c740f717ba3)

**Comment by KrychkovskaVira** [comment]
Hi @Dmytro-Kucherenko! Could you please fix it for mobile and tablet devices as well as it still reproduce? 

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/88768615/60f40455-0123-42b3-8483-fccbb967fd13)

**Comment by dmytro-kucherenko** [comment]
@KrychkovskaVira Thanks for noticing, separate pr was created

**Comment by dmytro-kucherenko** [comment]
@KrychkovskaVira The pr was merged, so you can test it

**Comment by KrychkovskaVira** [comment]
@Dmytro-Kucherenko it's fixed for all required resolutions except this one:

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/88768615/034ce5a2-1a1a-49c5-a91f-25950ff04586)
