### ISSUE TITLE
Add loader to chatbot messages

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2023-calmpal#446]
- [x] add loader when chatbot response is loading
- [x] don't allow user to send something in the chat during this time
- [x] add tooltip or subtitle for user, why they can't send messages

**Comment by HIMDanny** [comment]
@Liza-Veis, is it okay to have a loader like this?

![image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/58943798/db2e4f71-bf95-4f07-bfe3-88c8732c316d)

**Comment by liza-veis** [comment]
looks good

**Comment by HIMDanny** [comment]
@Liza-Veis, can we add a notification, when the user can't send the message?
![image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/58943798/6d6e9ebf-2126-4ebe-81e9-72ed606531bc)

**Comment by liza-veis** [comment]
Yes

**Comment by KrychkovskaVira** [comment]
@HIMDanny  Currently, the "Send" button is active even when sending a message is not possible, and a hand cursor is displayed. This issue can be fixed within this ticket or create a new one?

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/88768615/d63f5f66-efa7-4408-b7f2-ff30892e1ead)

**Comment by HIMDanny** [comment]
@KrychkovskaVira, I guess I can fix it in this issue and no need to create a new one

**Comment by KrychkovskaVira** [comment]
@HIMDanny I can see that the loader in the chat and the screenshot above appears different. I just want to confirm if this is planned: 

https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/88768615/c5c97ee9-20f8-4d3f-844e-9c31cbd785ad

**Comment by HIMDanny** [comment]
@KrychkovskaVira, sorry for the inconvenience, the loader in the chat is the right one

**Comment by HIMDanny** [comment]
@KrychkovskaVira, can I move this ticket to in progress column to fix the issue with send button?

**Comment by HIMDanny** [comment]
@KrychkovskaVira, we have one moment: when the button is disabled, the notification about an inability to send a message won't appear, because the form is disabled at this moment and we can't send anything

**Comment by HIMDanny** [comment]
here we have to quick options: disable the button but don't show the notification, or show the notification but don't disable the button

**Comment by KrychkovskaVira** [comment]
@Liza-Veis could you please clarify which option we are retaining? Since I previously inquired and received a response to make the button disabled

**Comment by liza-veis** [comment]
let's disable this button

**Comment by HIMDanny** [comment]
@KrychkovskaVira, please test the issue when you would have time

**Comment by KrychkovskaVira** [comment]
@HIMDanny right now there are 3 circles in the loader here, but in the chat, there are 4 shown
@Liza-Veis сan we leave it as it is, since it doesn't affect the perception of the loader?

**Comment by liza-veis** [comment]
yes

**Comment by HIMDanny** [comment]
@KrychkovskaVira, the loader in the chat is the one that needs to be there. I have changed the loader after the discussion in the pr
