### ISSUE TITLE
[BUG] Meditation player is not responsive to height changes

### ISSUE THREAD

**Issue by k-mlch** [BinaryStudioAcademy/bsa-2023-calmpal#463]
**Description:**
The meditation player is not responsive to height changes

**Environment:**
Chrome, Safari

**Visual Proof (screenshots, videos, text):**

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140718705/34403afa-7b95-47a9-98b1-5b3decb39906)

**Comment by oksana-mlynska** [comment]
@juanc-escobar the player is responsive now but why is it changing it's background color to pink? Is it an expected behaviour?
@k-mlch maybe you know?



https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140756353/abfb5924-3c70-49c2-80ca-bb5642bee042

**Comment by k-mlch** [comment]
@oksana-mlynska i'm not sure, i've never seen this behavior before (i assume it's because now the background adapts to the screen changes too)

**Comment by oksana-mlynska** [comment]
@Liza-Veis is it an expected behaviour about the changing of a background color?

**Comment by liza-veis** [comment]
No, this should be fixed
