### ISSUE TITLE
[BUG] The audio list does not open when the user clicks on the 'Meditation' tab while meditation player is opened

### ISSUE THREAD

**Issue by KrychkovskaVira** [BinaryStudioAcademy/bsa-2023-calmpal#476]
**Description:**
The audio list does not open when the user clicks on the 'Meditation' tab while meditation player is opened

**Preconditions:**
1. User is signed in
2. Meditation & Breathing page is opened on 'Meditation' tab

**Steps to reproduce:**

1. Click on the 'Play' button' on 'Atwined' meditation
2. Click on the 'Start with default duration' button
3. Click on the 'Meditation' tab
4. Pay attention that meditation list is not opened

**Actual Result:**
The audio list does not open when the user clicks on the 'Meditation' tab while meditation player is opened
**Expected Result:**
The audio list is displayed when the user clicks on the 'Meditation' tab while meditation player is opened
**Visual Proof (screenshots, videos, text):**

https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/88768615/70d3886b-d0a2-4857-a288-e8b6c471da0b

**Severity:**
Major (S2)

**Comment by OlenaYatseniuk** [comment]
@KrychkovskaVira Hello! I will fix this bug in #447
