### ISSUE TITLE
Add plan preview for unsubscribed users

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2023-calmpal#481]
- [x] remove subscribe button from current view
- [x] display proper time in Plan renews on
- [x] add another view for unsubscribed users
     - [x] take features from the current view, not from design
     - [x] rename `Update plan` to `Subscribe`, should take user to the same screen as before
     - [x] rename `6 month` to `Monthly`
     - [x] use actual price, not from the design
- [x] change hover effects on buttons, should be the same as in our main figma file

[figma](https://www.figma.com/file/Mwb2NT7u8o9WAvCDVlzylu/My-Subscriptions?type=design&node-id=0%3A1&mode=design&t=zCMmGHZDMX1J7Pkz-1)

<img width="169" alt="Screenshot 2023-09-28 at 19 58 55" src="https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/64521658/5ee4bcd1-4b80-42a9-b4ec-a5d3e11a5ba1">

**Comment by HIMDanny** [comment]
@Liza-Veis, could you clarify some points from the task, please?
1. remove subscribe button from the current view. Do you mean it should look like this?
![image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/58943798/7e3c919f-61df-49b9-9242-c1ba9ed32b00)
2. add another view for unsubscribed users. Did I understand it correctly that for the user who has a subscription, we show the subscription management dialog without the subscribe button, and for the not subscribed user we show another view?
- Has subscription
![image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/58943798/7e3c919f-61df-49b9-9242-c1ba9ed32b00)
- Doesn't have the subscription
![image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/58943798/540bd36a-0e8b-4747-9114-17f7c56b28ca)

**Comment by liza-veis** [comment]
1. yes
2. yes

**Comment by HIMDanny** [comment]
thanks))
