### ISSUE TITLE
Preferences step

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2023-calmpal#49]
- [x] Design
- [x] User should be able to select multiple items
- [x] When Other item is selected, textarea should appear
- [x] Textarea max length is 1000 characters
- [x] At least one category is required 
- [x] If Other item is selected, textarea is required
- [x] When Continue button pressed, the appropriate request should be made to save data
- [x] After saving data, user should be redirected to home screen
- [x] If authenticated user has isSurveyCompleted flag set to false, they should be redirected to this screen

Note: we will store selected items as an array of strings

![Sign up](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/64521658/64a0e15e-5bc5-474e-aa11-106b14693283)
<img width="500" alt="Screenshot 2023-08-22 at 18 21 06" src="https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/64521658/9abea86e-cdf0-4f13-98b2-3b7e74af8719">

User stories:
As a user, I can choose my preferences so that I can customize the application according to my specific needs and preferences, enhancing my overall user experience

Acceptance criteria:
1. The user should be able to select multiple items from the provided list
2. The selected items should remain highlighted or marked
3. When the user selects the "Other" item, a textarea should dynamically appear
4. The textarea should have a maximum character limit of 1000
5. The user should be able to enter text into the textarea
6. If the user selects the "Other" item, they should receive a validation message indicating that filling out the textarea is mandatory
7. The user should not be able to proceed to the next step without providing content in the textarea
8. After the user's design selections are saved, they should be redirected to the application's home screen

**Comment by dmytro-kucherenko** [comment]
@Liza-Veis Should I do validation of question options and textares using useAppForm?

**Comment by liza-veis** [comment]
@Dmytro-Kucherenko yes

**Comment by dmytro-kucherenko** [comment]
@Liza-Veis I want to make sure that in order to save data (defo after the backend part will be done) I will have to store this data in auth slice, create survey slice or should it be done another way?

**Comment by liza-veis** [comment]
Let's create another slice called survey
