### ISSUE TITLE
Survey

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2023-calmpal#50]
- [x] Add endpoint to save survey `/sign-up/survey`
 - [x] Each question in a survey will have its own key, for now, we will have only one - preferences
 - [x] Create a table in database called surveys with the following schema:
```
id: number unique
user_id: number unique
preferences: array of strings, max length of each value - 1000
```
 - [x] Add `is_survey_completed` flag to user_details table
 - [x] Return this flag when getting user
 - [x] Update database schema in readme
 
![Sign up](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/64521658/9255fa44-26b7-4016-abe2-664839a6a65e)

**Comment by OlenaYatseniuk** [comment]
@Liza-Veis  Could you, please, tell me which instrument you used to write the db schema in readme.md, because I haven't done it before?

**Comment by liza-veis** [comment]
@OlenaYatseniuk it's called mermaid, it has very simple syntax

**Comment by k-mlch** [comment]
Found issues:

**1. When the user tries to add the survey to the user that already has a survey added** 

Expected Result: No errors are shown, the survey data should be overridden
Actual Result: 500 Server Error returned

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140718705/1b8ca0d1-3234-48a0-9cac-a22c7f66bf28)

**2. When into number field (e.g. ID) sent string data**

Expected Result: 400 Bad Request + appropriate explanatory message
Actual Result: 500 Server Error returned

**3. When the field is missing in the body request**

Expected Result: 400 Bad Request + appropriate explanatory message
Actual Result: 500 Server Error returned

**4.  When the body is missing in the request**

Expected Result: 400 Bad Request + appropriate explanatory message
Actual Result: 500 Server Error returned

**Comment by OlenaYatseniuk** [comment]
@Liza-Veis  Hi! Could you, give me some clarification?
About 1 issue:
I thought we wouldn't be able to override the survey preferences as it is shown only before signing up. This means that the user couldn't see it after he register. If I am mistaken, please, correct me.
About rest issues:
I created the Joi validation schema and want to ask if it is OK to return 422 Error instead of 400. Because I see that in our project now it works so?


![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/102380564/6567ee12-9338-4d2b-9ef9-62e7f8d82c22)

**Comment by liza-veis** [comment]
1. let's make it possible to override
2. yes, let's return 422

**Comment by OlenaYatseniuk** [comment]
Okay, got it!

**Comment by OlenaYatseniuk** [comment]
All issues were fixed.
https://user-images.githubusercontent.com/102380564/264415620-79242d11-6780-45c5-8733-1b87a3a64315.png
https://user-images.githubusercontent.com/102380564/264416363-7c18248c-a040-4f79-ade5-1768cc44aecc.png
https://user-images.githubusercontent.com/102380564/264416465-85931166-8f33-484e-b0fd-39478b56bd7c.png
