### ISSUE TITLE
Preferences step

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2023-calmpal#51]
- [x] Design (we have only web design, so please adapt it)
- [x] Instead of header, add Sign In button at the bottom
- [x] User should be able to select multiple items
- [x] When Other item is selected, textarea should appear
- [x] Textarea max length is 1000 characters
- [x] At least one category is required
- [x] If Other item is selected, textarea is required
- [x] When Continue button pressed, the appropriate request should be made to save data
- [x] After saving data, user should be redirected to home screen
- [x] If authenticated user has isSurveyCompleted flag set to false, they should be redirected to this screen

Note: we will store selected items as an array of strings

![Sign up](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/64521658/64a0e15e-5bc5-474e-aa11-106b14693283)
<img width="500" alt="Screenshot 2023-08-22 at 18 21 06" src="https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/64521658/9abea86e-cdf0-4f13-98b2-3b7e74af8719">

User story:
As a user, I can choose my preferences so that I can customize the application according to my specific needs and preferences, enhancing my overall user experience

Acceptance criteria:

The user should be able to select multiple items from the provided list
The selected items should remain highlighted or marked
When the user selects the "Other" item, a textarea should dynamically appear
The textarea should have a maximum character limit of 1000
The user should be able to enter text into the textarea
If the user selects the "Other" item, they should receive a validation message indicating that filling out the textarea is mandatory
The user should not be able to proceed to the next step without providing content in the textarea
After the user's design selections are saved, they should be redirected to the application's home screen

**Comment by iamAlinaaa** [comment]
@Liza-Veis i have several questions according to this task

**Comment by iamAlinaaa** [comment]
@Liza-Veis i have several questions according to this task )

1. "At least one category is required (each category will have its key)" - is it mean that user should chose at leas one option ? and if nothing would be chosen then user would get notification (or the button will be disabled).
2. Where should i take questions (options) for survey from ?
3. "When Continue button click, the appropriate request should be made to save data" - where data should be saved for now ?
4. Should i make only one survey screen for now, or should next screen apear after user clicks continue ?

**Comment by liza-veis** [comment]
@iamAlinaaa 
1. yes, disable the button in this case
2. for now we will only have one screen with preferences (that's why it was updated, to simplify the logic), you can use question from figma
3. for now, you can just prepare everything before backend part is ready in this task #50 
4. yes, only one for now

**Comment by iamAlinaaa** [comment]
@Liza-Veis i want a bit more clarification, please )
"After saving data, user should be redirected to home screen" - i guess we dont have home screen component for now , or should i somehow leave it and mock up this home screen ?

**Comment by iamAlinaaa** [comment]
@Liza-Veis and one more question )

**Comment by iamAlinaaa** [comment]
@Liza-Veis and one more question )
if there will be several screens for survey, how should i name components? preferences-step-1 , preferences-step-2 and so on, or some other way ? or it shouldnt be on different screens (i mean all preferences steps)

**Comment by liza-veis** [comment]
Hey) each step will have it's own name, this step name is preferences

**Comment by liza-veis** [comment]
About redirecting after saving, you can redirect to the root page (it will be our home page)

**Comment by iamAlinaaa** [comment]
@Liza-Veis if user selects  "Other" category is she/he able to select another categories?

**Comment by liza-veis** [comment]
Yes, user still should be able to select multiple categories

**Comment by iamAlinaaa** [comment]
@Liza-Veis i have small question about layout : "Instead of header, add Sign In button at the bottom" - is this means that big sign in button should be added in the bottom ? or i should make it like link ? or maybe its better to make it in the top right corner?

**Comment by liza-veis** [comment]
I meant to add it to the bottom as usual full width button but maybe with another color. But you can choose any option that you suggested)

**Comment by iamAlinaaa** [comment]
@Liza-Veis  i have it like this now ( button continue is not styled because im waiting for Sign up screen branch #23 to be merged to add component improvements ). and styling depends on purposes, because if we will have this survey as obligatory and for even not signed up ( signed in) users, i would recommend to add sign in button to the bottom for everyone notice it. but i guess this survey is mostly for signed up users so the button can be not that noticable
![Снимок экрана 2023-08-24 210114](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/111873795/57f9db61-1ad9-488c-86fc-20de28212be0)

**Comment by liza-veis** [comment]
We will have this survey only for registered users
