### ISSUE TITLE
Chat screen

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2023-calmpal#54]
- [ ] Implement chat screen
- [ ] Use mocked data for chat items (leave at least one for testing)
- [ ] Add search by name (should be case insensitive)

![Chat](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/64521658/fc104e96-c6a5-4400-b3cf-074ec53b175e)

User story:
As a user, I want to see chat items and be able to use search on the Chat screen so that I can quickly find the needed conversatins by name.

Acceptance criteria:
1. Chat items should be displayed on the Chat screen
2. User should be able to search specific chat by entering input to the search field on the Chat screen
3. Search must be case insensitive

**Comment by Vika030718** [comment]
I have created a chat screen, now it looks like this.

Note 1:  We have changed the word 'topic' to the word 'chat' in the search field and in the link. This was approved by coaches. 
Note 2: Arrows were removed from the chat item on purpose.

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/4521937/c4c8d0fd-f441-4fe3-a1d9-ba14dbbd1869)

To QA Meam: It also has a bug for now - the title should be Chat, but not Chat List. Could you please create a ticket for this?
