### ISSUE TITLE
Add chat sidebar

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2023-calmpal#55]
- [x] Implement chat screen
- [x] Use mocked data for chat items (leave at least one for testing)
- [x] Add search by name (should be case insensitive)
 
<img width="238" alt="Screenshot 2023-08-22 at 19 01 28" src="https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/64521658/b2aa8794-054c-4efd-b8c1-e1ec198e5418">

User story:
As a user, I want to see chat items and be able to use search on the Chat sidebar so that I can quickly find the needed conversatins by name

Acceptance criteria:
1. Chat items should be displayed on the Chat screen
2. User should be able to search specific chat by entering input to the search field on the Chat sidebar
3. Search must be case insensitive

**Comment by Ekit18** [comment]
@Liza-Veis  as i understood i should also add chat screen like this?

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/92929504/38489a15-5151-4196-b8a8-89837285ff8c)

**Comment by liza-veis** [comment]
Hey) no, only chat selection part

**Comment by Ekit18** [comment]
What type should be array of chats?
This will be good for now?
{
id:number;
chatName:string;
}

**Comment by liza-veis** [comment]
You can see how it will be stored in the DB schema in the readme, you can leave only properties you need

**Comment by Ekit18** [comment]
@Liza-Veis for this task i need input, but common input in project has mandatory fields like control, errors and name. so can i make them optional and add field classname, function onChange and property value?

**Comment by liza-veis** [comment]
No, all the fields should be controlled by useForm, even search field

**Comment by liza-veis** [comment]
Also it's better to create a separate component here - search, it's ok if we need to duplicate some styles from input

**Comment by k-mlch** [comment]
@Ekit18 hi! after i pulled the last changes from git i still don't see the chat button on the sidebar (in order to navigate to the chat page), was it added?

**Comment by k-mlch** [comment]
fyi: This ticket will be tested once [another ticket](https://github.com/orgs/BinaryStudioAcademy/projects/12/views/1?pane=issue&itemId=37694041) is implemented and tested
