### ISSUE TITLE
Profile settings sidebar

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2023-calmpal#61]
- [x] Add profile settings sidebar
- [x] For now add only Sign Out option (log out on design) 

<img width="251" alt="Screenshot 2023-08-23 at 15 39 47" src="https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/64521658/7bcd6788-16ff-459a-b916-89372059540b">

**User story:**
As a user, I want to be able to navigate through profile settings so that I can quickly get to the needed option and adjust the application settings to my personal needs.

**Acceptance criteria:**
- The profile settings sidebar should be reachable from the main navigation menu.
- The first option from the Profile settings sidebar should be active when the user opens this page for the first time
- If a user clicks on the option from the profile settings sidebar, the appropriate page is opened and the option becomes active
- The active state of the selected option is saved if a user navigates to other menu sections
- The hover effect over the sidebar options is present
- The Profile settings sidebar is responsive for various screen sizes.
- On the mobile screen size user should be able to navigate back to the sidebar from the corresponding profile settings page

**Comment by vladyslavdobychin** [comment]
High-level plan for implementation: 

- [x] Locate the proper place/module where to put a new sidebar 
        -         src/libs/components/
- [x] Check other team members' PRs to locate common styles 
        -       Checking task/cp-32-add-header-component
- [x] See if any existing component could be re-used

**Comment by vladyslavdobychin** [comment]
Questions to be resolved: 

**Colors:** 
- What color to use for .container class? Currently #e5f0ff is taken from Figma. 
- For .user-name class the --black variable is used, while in Figma #1A141F (Seemed quite identical) 
- For .profile-button class the rgb(255 255 255 / 50%) from Figma for background-color was used, could not find alternative in variables. 
- For .profile-button class #e5e1ff was used for box-shadow, the closest color is --white-alpha-80

**Components structure**
- In Figma, all Profile Settings button have a place for the indicator of currently active option, should it be added for Sign Out? Or maybe to ProfileSettingsButton to make it a generic component for the future buttons?
<img width="575" alt="Screenshot 2023-08-25 at 15 24 25" src="https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/62558753/53e254e6-53d1-42f3-b653-0a1c5170a348">

**Comment by liza-veis** [comment]
Colors:

if we don't have some colors in common variables, then it's better to use similar colors if we have them in variables, if not, then create new variable

Components structure: 

yes, this should be a common component like sidebar-item, and let's just add property like - showArrow (false by default), and we will set it to true when item is active, but it will be always false for sign out

**Comment by vladyslavdobychin** [comment]
The way the component currently looks:
In next commits will be adding an arrow that will distinguish an active option
<img width="346" alt="Screenshot 2023-08-30 at 15 56 10" src="https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/62558753/01ad2503-bb3b-447d-8793-06c07a673796">

**Comment by vladyslavdobychin** [comment]
Added the arrow, now will be working on adding logic for displaying the arrow on the active option only
<img width="347" alt="Screenshot 2023-08-30 at 16 59 19" src="https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/62558753/67147473-43d2-4ed4-998e-a1d23a932299">

**Comment by vladyslavdobychin** [comment]
Added draft logic for marking active button, tested for text not taking more space that needed, made sure that active arrow will not be placed on Sign Out 

https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/62558753/30d75579-80ab-466d-95eb-216a4a1f9eba

**Comment by vladyslavdobychin** [comment]
Added logic for displaying the active state with an arrow + shadow, made sure that the shadow does not disappear if you click away and that it won't be applied to the sign out button. 

https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/62558753/ba72740b-7bd5-431b-80d0-7b56403931d7

**Comment by vladyslavdobychin** [comment]
https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/62558753/da3dc9d3-b792-4d11-a14c-8ae7b35362af

**Comment by oksana-mlynska** [comment]
@vladyslavdobychin In other sections if I choose some option on the sidebar, then go to another section and back, my chosen option stays active. With option Notifications and Reminders it doesen't work this way. 

https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140756353/370f05fd-c204-4189-bc5d-9f025c08448b

**Comment by oksana-mlynska** [comment]
@vladyslavdobychin could you give me the latest update conserning this blue arrow that was suppose to point on chosen option? Have we decided to make design without it?


![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140756353/f656d68b-4cee-4d02-a549-5313d7d0e18c)

**Comment by vladyslavdobychin** [comment]
Good afternoon, @oksana-mlynska 

1. Yes, you are correct, I simply haven't added this functionality initially. It was accounted to highlight only that option that was clicked manually. Do I get it right, that there should be some sort of a default active option in each sidebar? If you let me, I'll go back and add it. I'm just not sure what the procedure is. 
2. Per Liza removed this functionality, she stated that it will be added later.

**Comment by oksana-mlynska** [comment]
@vladyslavdobychin as I see from other sections (chat and meditation), the first one is active by default. Which makes sense, because something should be shown on the page (not a blank page until the user chooses the option). 

@Liza-Veis could you confirm? Should the first option on the sidebar be active by default until the user chooses the other one?

**Comment by liza-veis** [comment]
Yes, that's right

**Comment by vladyslavdobychin** [comment]
I think you are correct, I just treated the first button in the list as a demonstration of how the active state on a button needs to look. 
I went back to the code base and already found a solution on how to fix it. 
@oksana-mlynska would you be so kind to remind me what steps I need to perform at this point? 
It's my first fix technically. 
Should I create a new branch, fix what must be fixed and create a new PR for this?

**Comment by oksana-mlynska** [comment]
@vladyslavdobychin then let's make the first option active by default and save the chosen option in case the user switches between sections. I'll move this issue to 'To do' column, you can move it to 'In progress' when you are ready to work on it.

**Comment by oksana-mlynska** [comment]
@vladyslavdobychin Yes, it should be a new PR with fixes.
@Liza-Veis Am I right?

**Comment by vladyslavdobychin** [comment]
@oksana-mlynska just in case: 
Is that the only issue you've found? 
If yes I'll get to work right after Liza's approval. If not, I think it would be sensible to wait until you have concluded your testing and in case you find any other, extra issues, I could address them all at once.

**Comment by oksana-mlynska** [comment]
@vladyslavdobychin yes, sure. I am still testing and will add all comments here. I noticed that the bell on the icon is not located in the center, which is the designer's issue as on figma it looks the same. @Liza-Veis maybe we can fix it on our layout or is it not critical?


![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140756353/543ad183-3081-4cc4-bc8f-1cdd4ec5ea4c)

**Comment by oksana-mlynska** [comment]
@vladyslavdobychin have we decided not to change the location of the bell on the icon and leave it as it is?

**Comment by vladyslavdobychin** [comment]
@oksana-mlynska in the [PR](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/pull/258#issue-1892657583) I have mentioned this issue, but it was still merged. So I guess we are going to leave it as it is. 
But I still think that we can quadruple check with @Liza-Veis

**Comment by oksana-mlynska** [comment]
@vladyslavdobychin ok, then let's leave it as it is.
