### ISSUE TITLE
Chat layout

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2023-calmpal#65]
- [x] Build basic chat layout without dividers (all data will be mocked)
- [x] Add input field and send button at the bottom
- [x] Message is required field
- [x] When user presses send button, the message should appear on the screen
- [x] User should be able to get to this screen by clicking item in sidebar #42 

![Message Panel](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/64521658/c35251e3-2fcf-43d5-b104-a13018b6ccf4)

**Comment by v0ldemar01** [comment]
@HIMDanny we got the issue with crypto lib in deployment. Let's replace it
![image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/43109766/38bb9e22-fc53-41ab-b048-c8d8d4ce9fbf)

**Comment by v0ldemar01** [comment]
<img width="688" alt="image" src="https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/43109766/69916de5-687f-48ba-bc5f-e4a2030bf54e">
http://development.app.calmpal.com/

**Comment by HIMDanny** [comment]
@v0ldemar01, I guess I will completely delete this helper because it is only used in mocked data, if I'm not mistaken. I can do this in the issue #236

**Comment by v0ldemar01** [comment]
@HIMDanny got it

**Comment by KrychkovskaVira** [comment]
Hi @HIMDanny! I have a few comments regarding how the chat is displayed:

1. First write the user and then AI responds, in other words, when the user opens the chat for the first time, there should be no messages
2. Add a hover effect to the "Send" button.
3. When the input field is empty, the 'Send' button should be disabled
4. When user presses send button, the message should appear on the screen

**Comment by HIMDanny** [comment]
Hi, @KrychkovskaVira! Thanks for your comments.
1. I made this in my issue #236
4. I removed some logic because we are working on them in other tasks. So the messages would appear on the screen again in issue #190

About 2 and 3. @Liza-Veis, can I quickly do this in #236?

**Comment by liza-veis** [comment]
yes

**Comment by HIMDanny** [comment]
@Liza-Veis, I added a hover, but I think that we can disable a button after we would have validation for chat message input in #190

**Comment by KrychkovskaVira** [comment]
@HIMDanny Thank you for the answers. If this will be implemented in other tickets, I will close the ticket.
