### ISSUE TITLE
Add meditation_topics and meditation_entries tables

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2023-calmpal#67]
- [x] add meditation_topics table as in db schema
- [x] add meditation_entries table, everything except (image_id)

**Comment by oksana-mlynska** [comment]
@Liza-Veis did you mean in meditation_topics table everything except image_id? Because there's no field image_id in meditation_entries table.

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140756353/6615781b-4fed-4897-8851-266a674cec44)

**Comment by liza-veis** [comment]
@oksana-mlynska meditation_topics is another table 
<img width="108" alt="Screenshot 2023-08-29 at 19 36 30" src="https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/64521658/0efeadd2-8598-4cca-94fc-7a25fbfc9ec2">

**Comment by oksana-mlynska** [comment]
@Liza-Veis yes, so the task should be 
add meditation_topics table as in db schema, everything except (image_id)
add meditation_entries table  as in db schema

if this is correct, I'm closing the issue
