### ISSUE TITLE
Meditations list layout

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2023-calmpal#71]
- [x] Implement Meditations list layout
- [x] Use mocked data for now
- [x] User should see this page when he selects meditations item in sidebar

Note: Items will be added to the bottom, so this needs to be taken into account in the layout

![Meditation   Breathing](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/64521658/869f3ce0-8d1e-4d77-8b2c-8d1e4840b6d1)

**Comment by Xxandder** [comment]
Hi, I wanted to clarify several points before starting.
1. Do items or play buttons need to be links so user can go tho the song page? 
2. In the note where items will be added to the bottom, do you mean that in case when items number is small they will be added to the bottom of a list like on the screen?
3. Do all items(header, time, play button need hover effects?)

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/111736110/943ac2f2-06f1-4239-84dc-1b4940c3fd6d)

**Comment by liza-veis** [comment]
Hey!
1. yes, play button should be a link
2. I mean that if we have 9 or more elements, layout shouldn't be broken, and top elements should not change their positions (be shifted to the top)
3. only play button, because it will be a link

**Comment by Xxandder** [comment]
Thanks

**Comment by Xxandder** [comment]
Should I also implement topics block in collaboration with #78 assignee?

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/111736110/f619e565-5ac0-4a65-bc12-2e9f6a8e425a)

**Comment by Xxandder** [comment]
I need only layout, no changes in store/actions etc.? If yes than just  create objects for mock?

**Comment by Xxandder** [comment]
Duration format is only "X mins" ? Or it can be like 9 mins 30 sec?

**Comment by Xxandder** [comment]
Am I right that we won't get background image links from backend but it will be generated in frontend side?

**Comment by Xxandder** [comment]
May I change structure of element in mobile version? For example change size of icon and its position?
Also may I add hover effect on entire track item? I want to add border and some animation

**Comment by liza-veis** [comment]
> Should I also implement topics block in collaboration with https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/issues/78 assignee?

no

>I need only layout, no changes in store/actions etc.? If yes than just create objects for mock?

yes

> Duration format is only "X mins" ? Or it can be like 9 mins 30 sec?

we have no requirements to this, but we will get this from backend, so just use mocked data

> Am I right that we won't get background image links from backend but it will be generated in frontend side?

we will get them from backend

> May I change structure of element in mobile version? For example change size of icon and its position?

No, but you can write what you want to change in internal_chat and I may create a ticket for this

> Also may I add hover effect on entire track item? I want to add border and some animation

 it's better to add hover effect only to play button because it will be clickable, for other elements I would prefer to leave as it is, but maybe we will change this in future

**Comment by Xxandder** [comment]
Ok, thank you for the answers

**Comment by Xxandder** [comment]
Hello, also wanted to ask, if our website is 1440px width? In figma we have 1440px mockup but on our current website I see that it takes all screen width

**Comment by Xxandder** [comment]
I want to make it responsive but I don't have sidepar with categories list. So Do I need to just set margin-left to move meditation list to the right?

**Comment by liza-veis** [comment]
No, don't add margin, just do it like there is no sidebar with categories list

**Comment by Xxandder** [comment]
@Liza-Veis What about width of all app? It should be 100% of screen or 1440px like in mockup?

**Comment by Xxandder** [comment]
And in case when there is an odd number of items, whould I make size of the last item equal to others? And How I should  position it?

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/111736110/b9fa4bc7-aa71-4efa-95b6-95a150f0f95b)

**Comment by Xxandder** [comment]
And is it ok to use adaptive and not only responsive?

**Comment by liza-veis** [comment]
1. card should have the same width
2. they should look good on up to 320px (width)
3. we should have a fixed container, so if we have large screen they should look like in figma with fixed container width (don't stretch them)
4. if we have an odd number of cards, they still should have the same width, without stretching

**Comment by Xxandder** [comment]
Sorry, but I have some more questions)
1. But how I can set the same width for a card for 320px screen? In figma we have 451px card width. Or it was about that all cards need to have the same width but it can be changed according to responsive/adaptive design?
2. About container and app width. In figma app width- 1440px. So in case when the screen is bigger than 1440px - do I need to center it and have blank spaces for left and right sides?  And then I will be able to set 1002px meditation list container
3. I understood that I don't need to strench it, but do I need to center it or leave on the left like in case when in row both items are present?

**Comment by liza-veis** [comment]
1. I mean that all cards should have the same width, like if two top cards has width 300px, then the last card should also be 300px
2. yes, let's center the container 
3. container should be centered, but items in the container should be alligned to the left side

**Comment by Xxandder** [comment]
My apologies, but I want to clarify about the container, bacause I am not sure we speak about the same. On the screen you can see almost 1920px browser screen. And now we have website that is stretched to entire width, so I need to reduce the width to 1440 for entire app?

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/111736110/cae715ab-e276-40d4-8d37-aa63a9f14408)

**Comment by liza-veis** [comment]
I was thinking about making it like on the screenshot, where we have navigation and header sticked to the page borders, and a container with content that is centered
<img width="575" alt="Screenshot 2023-08-29 at 23 27 29" src="https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/64521658/3b8acebd-e7a2-4ab1-bbd5-ef1e2ed07424">

But maybe it would be better to fill the whole screen for the meditations page, so that we can have for example 3 columns. Let's do it this way and then for some layouts like settings we will have centered container

**Comment by Xxandder** [comment]
Ok, got it, thanks

**Comment by Xxandder** [comment]
And you said that there is no need to move it to the left with margin. But I want to use media-queries to make it responsive and without this shift I won't be able to do it properly, because in future it categories bar will be added and my layout will break.

**Comment by liza-veis** [comment]
I don't understand what margin do you mean

**Comment by Xxandder** [comment]
Oh, sorry. In mockup we have block with meditation categories and it takes 349px, I need to add meditation list, you said that I need to add like there is no such lcategories ist(actually we don't have it now). So should I just marging my meditation list to the right for emulation categories list presence? Because I need to set media queries, so I need to consider this 349px

**Comment by liza-veis** [comment]
you can use it, to setup media queries properly, but then remove this margin from layout in pr

**Comment by Xxandder** [comment]
Hello. I wanted to ask if it's possible to get background image for track without shadow aroung it? Because I can't set the background properly

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/111736110/3b473034-7bdc-4ae2-ac92-e627d5cd043a)


![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/111736110/f1e2af46-071c-4ca4-8c96-d6832d849b87)

**Comment by oksana-mlynska** [comment]
@Xxandder 'Play' buttons are not alligned when elements are located in one vertical line (column)


![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140756353/f94fba61-9c9f-4ff8-be78-433a3ec30c5b)
