### ISSUE TITLE
Add splash screen

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2023-calmpal#76]
https://www.npmjs.com/package/react-native-splash-screen

- [x] Add splash screen

Note: You can take app logo from frontend/assets/img/logo.svg

**Comment by k-mlch** [comment]
**Actual result:** We have a two splash screens one by one
https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140718705/0a164407-dd17-4306-a73b-87ccb8bb1a2c

**Comment by k-mlch** [comment]
**Actual result:** We have two splash screens shown one by one (look at the attached video)
**Expected result:** Only one splash screen should be shown

https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140718705/cbe20ab6-f451-4c2a-8484-3b71059d7b9f
