### ISSUE TITLE
Profile settings layout

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2023-calmpal#81]
- [x] Layout
- [x] Common checkbox component
- [x] Setting component (leave only Allow Notifications setting for now)  
![Message Panel](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/64521658/aa37888a-8930-4820-aac1-f5e6defc00d6)

**Comment by HIMDanny** [comment]
Should I create all the parts that are on the screenshot?
![image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/58943798/44bde17c-07ae-4a43-936f-a535ae708127)

**Comment by liza-veis** [comment]
No, we already have pr for Profile settings sidebar #61, so only page layout

**Comment by HIMDanny** [comment]
@Liza-Veis, would every setting have a checkbox?

**Comment by liza-veis** [comment]
I think no, we should consider this, we may have any other settings here

**Comment by HIMDanny** [comment]
@Liza-Veis, hey! Should I add an option to add the label like on this screenshot?
![image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/58943798/c3ca69e3-8330-486c-9f0d-3cc8ff588d94)

**Comment by HIMDanny** [comment]
I found some inconsistencies in the design of the switch checkbox. The colors of the turned-off switch in the UI Kit are different from the switch in the setting. What design do you think I should implement?
![image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/58943798/71704ab1-c722-40b9-b0c1-e2b9761eaa61)
![image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/58943798/3b6f5aed-ae9a-4268-8f19-ff706a4ae30c)

**Comment by HIMDanny** [comment]
@Liza-Veis, should I animate the switch toggle?

**Comment by liza-veis** [comment]
@HIMDanny hey! Let's use design from settings. If we have switches with labels somewhere in the design, then add them

**Comment by liza-veis** [comment]
Yes, please add basic animation to switches

**Comment by HIMDanny** [comment]
@Liza-Veis, should I create a page layout like a single Outlet for every setting (Notifications, Subscriptions, etc.) or just for Notification Settings?

**Comment by liza-veis** [comment]
let's do it without Outlet for now, just usual screen

**Comment by oksana-mlynska** [comment]
@Liza-Veis Have temporarily added a component on the root page locally for testing. Frontend looks like layout

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140756353/ddade0f2-fae8-498f-8f2f-e837b80c9160)

toggle switch works properly in Google Chrome but in Firefox it doesen't change its state when clicked. @HIMDanny could you check it out? I recorded a video



https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140756353/75ea7665-4fd1-466b-8eff-baac655ac819

**Comment by HIMDanny** [comment]
@oksana-mlynska, thank you for your attention, I will check this

**Comment by HIMDanny** [comment]
I found the solution. @Liza-Veis, can I fix this problem? I need only to push some changes

**Comment by oksana-mlynska** [comment]
@HIMDanny If you know how to fix it, I will move this task to the 'To do' column and from there as you are already assigned for it, you can move it to 'In progress' and work on it.

**Comment by HIMDanny** [comment]
deal, let's do this and I will create a pr ASAP

**Comment by oksana-mlynska** [comment]
I reopened the issue as I was told that we can't close anything that is not on staging. So I'll close it as soon as the component will be added on the profile settings page
