### ISSUE TITLE
Add user profile sidebar

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2023-calmpal#82]
- [x] Add user profile sidebar
- [x] User name should be taken from authenticated user
- [x] Add placeholder image instead of avatar
- [x] user should get to this page when he opens profile item
- [x] show Profile instead of Home in the header

![Dashboard](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/64521658/3041db06-9ce0-49b4-afbb-746c2118fc88)

User story:
As a user, I want to see my profile on the Home page so that I can easily access my personal information.

Acceptance criteria:
1. Placeholder image should be shown in the sidebar
2. Home page with Profile should be displayed after clicking on the Home item
3. When a user opens the Home page, the user's name retrieved from the authenticated information should be displayed in the sidebar

**Comment by liza-veis** [comment]
@KrychkovskaVira important update on this task, user should get to this page when he opens Home item, not Profile one

**Comment by KrychkovskaVira** [comment]
FYI: user profile sidebar shouldn't be created based on the information provided in this [ticket](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/issues/195)

**Comment by KrychkovskaVira** [comment]
@Liza-Veis could you please clarify whether "Home" or "Profile" should appear in the header?

**Comment by liza-veis** [comment]
Home
