### ISSUE TITLE
Clean up layout

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2023-calmpal#84]
- [x] remove users list and everything related to this (layout, slice, controller, service, repository)
  <img width="353" alt="Screenshot 2023-08-26 at 23 37 15" src="https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/64521658/fe6ecf3c-b71d-4221-99f7-0bb564d970b0">

- [x] remove links, current path, react logo
  <img width="448" alt="Screenshot 2023-08-26 at 23 35 39" src="https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/64521658/92a46cb1-481c-4749-be57-4b39910d01bf">
- [x] leave only one home option ('/')
  <img width="76" alt="Screenshot 2023-08-26 at 23 39 15" src="https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/64521658/041652d2-0867-4275-97c2-e8acba393f4c">

**Comment by dmytro-kucherenko** [comment]
@Liza-Veis Should I remove root component or just leave it empty?

**Comment by liza-veis** [comment]
Remove it
