### ISSUE TITLE
Improvements to sign up page

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2023-calmpal#87]
- [x] Set line-height to 1.2 for form title
  <img width="321" alt="Screenshot 2023-08-26 at 23 45 01" src="https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/64521658/d8e0d986-bfbd-4a04-b3f7-5d87ca84aa8f">
- [x] When error appears, borders of the input field should be rounded
  <img width="305" alt="Screenshot 2023-08-26 at 23 45 47" src="https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/64521658/7b93da0f-be8f-494e-8cb0-1ecb90f37609">
- [x] Align error message to the left
- [x] Add placeholder for password field
  <img width="309" alt="Screenshot 2023-08-26 at 23 47 03" src="https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/64521658/607a2193-97ec-4f69-b978-0a205e2a64e8">
- [x] Add font styles to input (color, font-family, line-height etc.) 
- [x] Default paddings should be like in figma -  70px 120px
- [x] Remove width, height, min-height properties from overlay 
- [ ] Adapt for all dimensions up to 320px (width)

**Comment by Nanaier** [comment]
@Liza-Veis hey - should I delete the sidebar and header from the app component, so the page looks organic?
