### ISSUE TITLE
Sidebar should have a fixed position

### ISSUE THREAD

**Issue by k-mlch** [BinaryStudioAcademy/bsa-2023-calmpal#91]
- [x] Sidebar should follow the scroll

**Comment by dmytro-kucherenko** [comment]
Also left icons aren't centered when there aren't three of them because of static gap

**Comment by Ekit18** [comment]
@Liza-Veis could you please clarify whether the sidebar should be scrollable and be over 100vh or that whole app stays bounded to 100vh and the char part of the page will scroll according to amount of messages similar to telegram

**Comment by liza-veis** [comment]
it should have 100% height and position sticky
