### ISSUE TITLE
The error message is not displayed on the ‘Sign up’ page after signing up with already registered e-mail

### ISSUE THREAD

**Issue by oksana-mlynska** [BinaryStudioAcademy/bsa-2023-calmpal#97]
**Description:**
The error message is not displayed on the ‘Sign up’ page after entering already registered E-mail to ‘E-mail’ field and clicking on ‘Sign up’ page

**Preconditions:**
The sign up page http://localhost:3000/sign-up is opened

**Environment:**
OS Windows 10
Browser Google Chrome 
Version 116.0.5845.111 

**Steps to reproduce:**

1. Enter valid data to the fields ‘Name’ and ‘Password’
2. Enter already registered e-mail to the field ‘E-mail’
3. Click on the ‘Sign up’ button

**Actual Result:**
No error messages are displayed informing the user that entered e-mail is already registered

**Expected Result:**
Error message is displayed informing the user that entered e-mail is already registered

**Visual Proof (screenshots, videos, text):**

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140756353/2e6138f0-8c76-4f9d-b11f-e3e7ba35f7cf)

**Severity:**
Minor (S3)

**Additional information:** 
The response body of the request is informing: "insert into \"users\" (\"created_at\", \"email\", \"password_hash\", \"password_salt\", \"updated_at\") values ($1, $2, $3, $4, $5) returning \"id\" - повторяющееся значение ключа нарушает ограничение уникальности \"users_email_unique\"".

**Comment by liza-veis** [comment]
Looks like this was fixed by https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/pull/90, but we need to check

**Comment by juanc-escobar** [comment]
Hi, I checked the code from my PR and did a test, It is successfully displaying the toast container with the error messages the backend assigned for auth duplicated user.

here is an image of multiple tries:



![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/107894952/45b5c999-902f-4ff2-a594-404ea9810674)





also as you mentioned in the cp-14: Add sign-up functionality they added an error message I attached an image:



![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/107894952/1387fc7a-2ff7-410a-86a6-139a7c8fdfaf)



even if there was no error message it should display: "something went wrong." 

maybe you can do a pull to update your code base, merge with the latest changes, and then install everything again:

1. Install dependencies: npm install.
2. Install pre-commit hooks: npx simple-git-hooks. This hook is used to verify code style on commit.
3. Run database. You can either run it in docker using command docker-compose -f docker-compose.yml up --build or by installing postgres on your computer. Docker variant is preferred.
4. Apply migrations: npm run migrate:dev -w backend
5. Run backend: npm run start:dev -w backend
6. Run frontend: npm run start:dev -w frontend
7. Run mobile: npm run start:dev -w mobile

**Comment by oksana-mlynska** [comment]
@Liza-Veis @juanc-escobar I pulled latest changes, deleted my old entries from database and now with new entries it works properly. Error message "User already exists" is displayed.
